### ISSUE TITLE
Configuration problems in different enviroments

### ISSUE THREAD

**Issue by awdng** [FriendsOfSymfony/FOSHttpCacheBundle#139]
Basically what ive tried todo is disable the caching stuff in the dev enviroment so that developers do not need to install and configure varnish etc.
This works when defining the routes in the config.yml and then setting the cache proxies in the config_prod.yml. Defining everything in the config.yml and then resetting fos_http_cache: ~ in the config_dev.yml did not seem to work, but this might be expected behavior in symfony.

The main issue is however, that calls to ```fos_http_cache.cache_manager``` fail with ```You have requested a non-existent service fos_http_cache.cache_manager``` exception when no proxy is defined in the current env (like dev). Of course wrapping the call in a try/catch block works, but is somewhat cumbersome. Setting invalidation.enabled to false also does not seem to change anything in this case.

**Comment by dbu** [comment]
moved to https://github.com/FriendsOfSymfony/FOSHttpCache/issues/172
