### ISSUE TITLE
Set option on Annotation to invalidate with BAN or PURGE

### ISSUE THREAD

**Issue by lepiaf** [FriendsOfSymfony/FOSHttpCacheBundle#160]
Hi,

When I use @InvalidatePath, It always use PURGE request. I would like to have a choice to do BAN or PURGE.

I suggest to add an option "type" : 

``` php
/**
 * @InvalidateRoute(name="some_route", params={"id" = {"expression"="id"}}, type="ban")
 */

/**
 * @InvalidateRoute(name="some_route", params={"id" = {"expression"="id"}}, type="purge")
 */

/**
 * @InvalidatePath(path="/some/path/.*", type="ban")
 */

/**
 * @InvalidatePath(path="/some/path", type="purge")
 */
```

Then, in InvalidateSubscriber it will switch between `$this->cacheManager->invalidatePath()` and `$this->cacheManager->invalidateRegex()`

What do you think ?

**Comment by dbu** [comment]
a simpler case could be to ban everything up to the first parameter. so for /products/{id} ban /products/ then we would only look at the pattern
