### ISSUE TITLE
Use tested config in our docs

### ISSUE THREAD

**Issue by ddeboer** [FriendsOfSymfony/FOSHttpCacheBundle#174]
What about including sections from our functional test’s `config.yml` [in our docs](http://foshttpcachebundle.readthedocs.org/en/latest/reference/configuration/headers.html), just like we’re now including tested VCL? That way we can be sure we don’t make any typos/mistakes in the doc sections.

**Comment by dbu** [comment]
fixed in https://github.com/FriendsOfSymfony/FOSHttpCache/pull/229
