### ISSUE TITLE
tagging response while building the content

### ISSUE THREAD

**Issue by dbu** [FriendsOfSymfony/FOSHttpCacheBundle#181]
We are looking into integrating this bundle with the cmf. One idea we had was to offer a twig function to register a tag from the templates (as cms can have complex structures and templates is the place we know what is really rendered). is that insane or a good idea? should we even offer something in here maybe?

A problem with that is that [tagResponse](https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/CacheManager.php#L54) requires to pass the Response object. when rendering in twig, that does not exist yet. Could we offer another method on CacheManager that adds a tag to a response listener and adds the tags at that point?

see https://github.com/symfony-cmf/symfony-cmf/issues/211 for other discussion

TODO
* [x] allow to set tags without having a response object => #182
* [ ] twig function for adding tags => #211

See #184 for the rest of the cmf related discussion.

**Comment by ddeboer** [comment]
#182 is done, so only the Twig extension remains. Should it go in the bundle or the library (or I guess ideally a separate twig-bridge package)? People may want to use the extension in a non-Symfony application.

**Comment by dbu** [comment]
i would put it into the bundle. its just a shortcut to call a php
function in the proper twig way. if somebody needs it outside the
symfony full stack context, he can either depend on the bundle
nontheless and bootstrap the extension himself, or simply copy the 10
lines of code, i would say.

**Comment by ddeboer** [comment]
Fair enough!
