### ISSUE TITLE
Integrate Symfony HttpCache purge and refresh

### ISSUE THREAD

**Issue by dbu** [FriendsOfSymfony/FOSHttpCacheBundle#183]
Once https://github.com/FriendsOfSymfony/FOSHttpCache/pull/150 is merged, integrate the purge and refresh subscriber and document them.

**Comment by ddeboer** [comment]
FriendsOfSymfony/FOSHttpCache#150 has been merged (and tagged) so we can proceed with purge and refresh support in the bundle.

**Comment by dbu** [comment]
@chirimoya do you want to pick this up and work on it?
