### ISSUE TITLE
Object invalidation

### ISSUE THREAD

**Issue by dantleech** [FriendsOfSymfony/FOSHttpCacheBundle#184]
It would be good to be able to pass an object to a / the cache manager and then have handlers which decide if they know how to invalidate that object / modify the response.

I have implemented this in [SuluCMF](https://github.com/sulu-cmf/sulu/pull/653)

The handlers have an API as follows:

```
$handler->updateResponse($response, $object);
$handler->invalidateObject($object);
```

A "Foobar" handler might look like:

``` php
class FoobarHandler implements HandlerInvalidatorInterface, HandlerResponseUpdaterInterface
{
    /**
     * @param CacheInvalidator FOS Cache Invalidator
     */
    public function __concstruct(CacheInvalidator $invalidator)
    {
        $this->invalidator = $invalidator;
    }

    public function supports($object)
    {
         return $object impplements Foobar;
    }

    public function updateResponse(Response $response, $object)
    {
         $response->set('X-Foobar', $object->getFoobar());
    }

    public function invalidateObject($object)
    {
        $this->invalidator->invalidateTags($object->getFoobar());
    }
}
```

There is also an `AggregateHandler`:

``` php
$aggregateHandler = new AggregateHandler(array(
     new FoobarHandler($cacheInvalidator)
 );

 $aggregateHandler->updateResponse(...);
 $aggregateHandler->invalidateObject(...);
```

 The aggregate handler would be used by default.

**Comment by dbu** [comment]
there is now a tag handler class that allows to add tags for the response even when the response object is not yet created. with #211 it will even be possible to tag from within a twig template.

@dantleech does that fit with your idea how things should be built? 

i think what is now missing is some sort of doctrine adapter that automatically handles invalidation and maybe can help with tagging based on objects. i am not sure whether that belongs into this bundle or would better fit into a separate CmfCacheBundle or similar.

**Comment by dantleech** [comment]
I think so..

**Comment by dbu** [comment]
i will close this and say we have the tools here - if somebody needs doctrine adapters and the like, that should be in a separate bundle to keep the scope of this bundle reasonable.
