### ISSUE TITLE
Tag annotation array can be confusing

### ISSUE THREAD

**Issue by ddeboer** [FriendsOfSymfony/FOSHttpCacheBundle#185]
We allow both multiple tags and the `expression=` syntax in the `@Tag` annotation. This results in some confusing behaviour:

These work:

``` php
@Tag("one")
@Tag({"one", "two"})
@Tag(expression="'one'~id")
```

While this one doesn’t:

``` php
@Tag({"one", expression="'one'~id"}) // throws [Semantical Error] Couldn't find constant expression
```

Should we drop `allowArray`, so there can be only one tag per `@Tag` line? Or is there another way to solve this problem?

**Comment by dbu** [comment]
i guess 2.0 would be the moment to possibly do something about this, if you see possible ways of action.

**Comment by ddeboer** [comment]
Thanks for the explanation, @stof. Actually, however, `@Tag({"one"}, expression="'one'~id")` only returns `one-123`. Anyway, I don’t think there’s anything we can do about this issue other than introducing a separate `@TagExpression` annotation, which is in itself confusing and inconsistent with our other annotations. If users run into trouble, we may want to add a note to the docs explicitly stating that you cannot combine expressions and strings in one tag array.
