### ISSUE TITLE
Register new proxy clients via service tag

### ISSUE THREAD

**Issue by dantleech** [FriendsOfSymfony/FOSHttpCacheBundle#186]
It would be cool to be able to register new proxy client implementations using a compiler pass.

Currently it is only possible to register a new proxy client via. convention, your service must be named as follows:

````
fos_http_cache.test.client.my_custom_client
````

Which breaks namespacing rules.

You could use tags to register new and existing proxy clients:

````
<service id="my_proxy_client" ... />
    <tag name="fos_http_cache.proxy_client"  alias="my_cool_client"/>
</service>
````

**Comment by dbu** [comment]
the services with `test` are only about the custom test case we provide. would make sense to be flexible there though.

for the CacheManager, i thought you can specify your own service for the proxy client. but i can't find that anymore so it looks like i was wrong. seems like we should allow to configure your own proxy client to be used with the CacheManager.

we do not provide a way to configure more than one client for the same cache (like 2 different varnishes with different roles). you can configure multiple ips and the client will send to all of those, but if you need a second client to talk to some other varnish system, you need your own service. but that really is an edge case.

so i think we don't need a compiler pass for that, the CacheManager only ever uses ONE client anyways. configuring a custom service name should be enough.

but for the testing i am less sure how that should work. where is that logic based on the service name?

**Comment by stof** [comment]
@dbu I'm not sure we need to expose a configuration for that. Overwriting the service with your custom one is simple enough:

And actually, it allows configuring both a nginx and a varnish proxy client (but the CacheManager will only use one of them)

**Comment by dbu** [comment]
@stof you mean overwriting the cache-manager server? well we could. but allowing to set a service id in the config is more obvious for the user i think. if we don't want to do that, we should at least explain the idea in the doc.

**Comment by stof** [comment]
no, I mean overwriting the proxy_client service if they want to use their own one

**Comment by dantleech** [comment]
@stof how do you reliably overwrite a service without adding a compiler pass?

But in our use case it would need to  be configurable. Saying enter "nginx" or "varnish" here, or if you want to use X then do something different isn't really a good UX. 

I would prefer that you could specify a named Client and that the configuration was open-ended so that  the DI / Configuration does not know of a difference between any of the proxy clients and third-party clients could be integrated transparently, but thats just my 2c and probably more trouble than its worth.

**Comment by dbu** [comment]
i agree with dan. feels awkward to abuse service fos_http_cache.proxy_client.varnish to talk to my squid or whatever i came up with for caching.
