### ISSUE TITLE
Documentation not clear

### ISSUE THREAD

**Issue by ericvincenterv** [FriendsOfSymfony/FOSHttpCacheBundle#188]
It is unclear in the documentation how to set up varnish/symfony to send the correct "user context hash".
On this page it says you need to set up a php file yourself : https://github.com/FriendsOfSymfony/FOSHttpCache/blob/master/doc/user-context.rst#returning-the-user-context-hash

However we seem to set up user_context_hash in varnish vcl  (set req.url = "/user_context_hash.php";) we always get the following error returned from the server : 

````
Not Found

The requested URL /user_context_hash.php was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.
````

Looking through the code there is no reference to /user_context_hash.php
Is there supposed to be a symfony route that handles the page automatically (/user_context_hash) ?

Can you please point us in the right direction ?

**Comment by ddeboer** [comment]
You’re referring to the [library docs for user context hash](http://foshttpcache.readthedocs.org/en/latest/user-context.html#returning-the-user-context-hash). Have you also the bundle docs on the subject, in particular [Context Hash Route](http://foshttpcachebundle.readthedocs.org/en/latest/reference/configuration/user-context.html#context-hash-route)?

**Comment by ericvincenterv** [comment]
I already have set up the same default route : 

````
# app/config/routing.yml
user_context_hash:
    path: /user-context-hash
````

In varnish i have tried : 
````
set req.url = "/user_context_hash.php";
````
and
````
set req.url = "/user-context-hash";
````

On each try I empty/restart varnish cache

Each time I get a 404 error.

I have allso tried bypassing varnish and accessing the site via app_dev.php/user-context-hash

I have the following error : 
````
Unable to find the controller for path "/user-context-hash". Maybe you forgot to add the matching route in your routing configuration? 
````
Is this is normal ?

**Comment by ddeboer** [comment]
Yes, that’s normal. Requests for a context hash must [have a special Accept header](http://foshttpcache.readthedocs.org/en/latest/user-context.html#overview). By default this is `application/vnd.fos.user-context-hash`. Have you configured Varnish for [setting that accept header](http://foshttpcache.readthedocs.org/en/latest/varnish-configuration.html#user-context) (line 23)?

**Comment by ericvincenterv** [comment]
Yes I have configured varnish accordingly, Is there a way to test that the right header is sent by symfony ?

**Comment by dbu** [comment]
have you [activated user context handling](http://foshttpcachebundle.readthedocs.org/en/latest/reference/configuration/user-context.html) in the bundle? it looks like the listener is not triggered.

@ddeboer we should probably add a note in http://foshttpcache.readthedocs.org/en/latest/user-context.html#returning-the-user-context-hash to explain that when using symfony, you should look at the doc for the bundle.

**Comment by ericvincenterv** [comment]
Yes I have activated user context handling : 
```` yaml
fos_http_cache:
    proxy_client:
        varnish:
            servers: (#My IP)
            base_url: (#My base URL without the "http://")
    user_context:
        enabled: true
        role_provider: true
    flash_message:
        enabled: true
        name: flashes
        path: /
        host: null
        secure: debug
````

I allso have this in my AppCache.php
```` php
<?php

require_once __DIR__.'/AppKernel.php';

use FOS\HttpCacheBundle\SymfonyCache\EventDispatchingHttpCache;
use FOS\HttpCache\SymfonyCache\UserContextSubscriber;

class AppCache extends EventDispatchingHttpCache
{
    /**
     * Overwrite constructor to register event subscribers for FOSHttpCache.
     */
    public function __construct(HttpKernelInterface $kernel, $cacheDir = null)
    {
        parent::__construct($kernel, $cacheDir);

        $this->addSubscriber(new UserContextSubscriber());
    }
}
````
Although I have a doubt on the use : 
use FOS\HttpCacheBundle\SymfonyCache\EventDispatchingHttpCache;
//use FOS\HttpCache\SymfonyCache\EventDispatchingHttpCache;

**Comment by dbu** [comment]
now you got me really confused. are you using varnish or the symfony built-in reverse proxy HttpCache? there is no point in using both together. they have the same job. HttpCache needs no sysadmin work, varnish is a lot more efficient as its a native application.

the HttpCache authorization event handler prevents user context lookups coming from outside. (it assumes that the outside is the internet, and we really must not expose context hashes to the internet) if you really have to use both caches, you must make up your mind in which cache you want the user context. but i would recommend to go with only varnish if you have the option of using varnish.

**Comment by ericvincenterv** [comment]
I want to use varnish only, not the built in reverse proxy, I am not sure what I am doing wrong.
Should the AppCache.php file be the original symfony file ?

I think this page is what tripped me : https://github.com/FriendsOfSymfony/FOSHttpCache/blob/master/doc/symfony-cache-configuration.rst#extending-the-correct-httpcache-class

**Comment by ddeboer** [comment]
> Should the AppCache.php file be the original symfony file ?

Yes. If you just want to use Varnish, you need to make none of the changes in the Symfony Cache Configuration chapter that you link to.

**Comment by ericvincenterv** [comment]
I reverted back to the original file : 
```` php
<?php

require_once __DIR__.'/AppKernel.php';

use Symfony\Bundle\FrameworkBundle\HttpCache\HttpCache;

class AppCache extends HttpCache
{
}
````

I am still getting 404s everywhere : "The requested URL /user-context-hash was not found on this server."

**Comment by dbu** [comment]
when using varnish, you should not even uncomment AppCache in web/app.php and stay with AppKernel directly (which is the default behaviour when starting with the symfony standard edition)

so you made the change to the varnish config to ask for /user-context-hash rather than with underscores, right? at some point you where at "Unable to find the controller" you said, which is better than the route not being found. varnish needs to send the request with the correct header for the listener to trigger, you can't do that with a web browser. if you left things at the default behaviour, you should be able to test this with `curl -v -H "Accept: application/vnd.fos.user-context-hash" http://localhost/user-context-hash` (or replace localhost with your hostname - but the point is to go directly to where symfony runs, not through varnish)

if that does not help, and you are back at the "no controller found", try to debug what happens inside [UserContextSubscriber](https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/EventListener/UserContextSubscriber.php#L84)

**Comment by ericvincenterv** [comment]
I try to look in "UserContextSubscriber.php" but I have the same problem :+1: 
"
Not Found

The requested URL /user-context-hash was not found on this server.
"
:-(

**Comment by ddeboer** [comment]
Are you sure that URL is actually landing at your Symfony app? The error sounds very much like it’s coming from Apache or Nginx; Symfony usually shows a different message. Have you checked your rewrite rules? If you add a `die('test');` to your `app.php`, do you see that when you go to `/user-context-hash` in your browser? What happens if you go to `/app_dev.php/user-context-hash`?

**Comment by ericvincenterv** [comment]
In my app.php, I have : 
`````
<?php

use Symfony\Component\HttpFoundation\Request;

$loader = require_once __DIR__.'/../app/bootstrap.php.cache';

require_once __DIR__.'/../app/AppKernel.php';

die('test');

$kernel = new AppKernel('prod', false);
$kernel->loadClassCache();
$request = Request::createFromGlobals();
$response = $kernel->handle($request);
$response->send();
$kernel->terminate($request, $response);
`````
I add "die('test');"

The result is : 
`````
test
`````

But : 
If I go to any URL, I have : 
`````
test
`````

URL : XXX/url-context-hash / result : test
URL : XXX/aaa / result : test
URL : XXX/app_dev.php/user-context-hash / result : test

**Comment by dbu** [comment]
sure. that was to check if you really go to the server you expect. but if you configured a route /user-context-hash, you really should see a symfony error that no controller was found, if the listener does not work, not just a route not found. are you sure you got `-` vs `_` right? if you do not go through app_dev.php, did you clear the prod cache after adding the route?

**Comment by ericvincenterv** [comment]
In my default.vcl, I have : 
`````
      set req.url = "/user-context-hash";
`````
So, I think it's good.

**Comment by dbu** [comment]
did you try clearing app/cache/prod? what do you see in prod.log after a request to /user-context-hash? if the problem is not something about controller not found but about no route found, then its a symfony setup issue

**Comment by ericvincenterv** [comment]
I can confirm that i have the following error : 
"Unable to find the controller for path "/user-context-hash". Maybe you forgot to add the matching route in your routing configuration?" when I try to access "/app_dev.php/user-context-hash" So I guess the listener is not working.

**Comment by dbu** [comment]
did you try like this `curl -v -H "Accept: application/vnd.fos.user-context-hash" http://localhost/app_dev.php/user-context-hash` ? (maybe need to replace localhost with your hostname)

**Comment by dbu** [comment]
so the route is there. now you need to know if the listener works. try with that request above , or try to put a die at the very beginning of UserContextSubscriber::onKernelRequest , try to see if you hit one of the return checks, ...

**Comment by ericvincenterv** [comment]
I try : 
"
curl -v -H "Accept: application/vnd.fos.user-context-hash" http://varnish.XXX.net/app_dev.php/user-context-hash
"

The result is : 
`````
<!DOCTYPE html>
<html>
  <head>
    <title>400 Bad Request</title>
  </head>
  <body>
    <h1>Error 400 Bad Request</h1>
    <p>Bad Request</p>
    <h3>Guru Meditation:</h3>
    <p>XID: 327742</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
* Connection #0 to host varnish.XXXX.net left intact
* Closing connection #0
`````

**Comment by ericvincenterv** [comment]
in UserContextSubscriber, in onKernelRequest, I add : 
```` php 
die("OnKernel")
````
The result is : "OnKernel"

in UserContextSubscriber, in getSubscribedEvents, I add : 
```` php 
die("OngetSubscribedEvents")
````
The result is : "OngetSubscribedEvents"

**Comment by dbu** [comment]
that sounds both expected. you want to send that curl request to your symfony application directly, not to varnish. the varnish config aborts if you try to send the request from outside: https://github.com/FriendsOfSymfony/FOSHttpCache/blob/master/tests/Functional/Fixtures/varnish-4/user_context.vcl#L6-L12

**Comment by ericvincenterv** [comment]
Ok, 

The this is the result when I call the webserver directly : 

```` 
* About to connect() to localhost port 80 (#0)
*   Trying ::1...
* connected
* Connected to localhost (::1) port 80 (#0)
> GET /varnish.XXXX.net/self/web/app_dev.php/user-context-hash HTTP/1.1
> User-Agent: curl/7.26.0
> Host: localhost
> Accept: application/vnd.fos.user-context-hash
> 
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 200 OK
< Date: Tue, 20 Jan 2015 14:12:13 GMT
< Server: Apache/2.2.22 (Debian)
< X-Powered-By: PHP/5.4.36-0+deb7u1
< X-User-Context-Hash: 5224d8f5b85429624e2160e538a3376a479ec87b89251b295c44ecbf7498ea3c
< Cache-Control: max-age=0, no-cache, private
< X-Cache-Debug: 1
< Vary: Cookie,Authorization
< X-Debug-Token: e09bed
< X-Debug-Token-Link: /varnish.XXXX.net/self/web/app_dev.php/_profiler/e09bed
< Transfer-Encoding: chunked
< Content-Type: application/vnd.fos.user-context-hash
< 
* Connection #0 to host localhost left intact
* Closing connection #0
````

**Comment by dbu** [comment]
ok, so this is working. see the `X-User-Context-Hash` header. 

so if your varnish config is correct, and you go to a real page that is protected, you should be able to use this feature now.

**Comment by ericvincenterv** [comment]
I will try, many thanks.
