### ISSUE TITLE
User context documentation tweaks

### ISSUE THREAD

**Issue by ddeboer** [FriendsOfSymfony/FOSHttpCacheBundle#189]
@dbu (in #188): 
> we should probably add a note in http://foshttpcache.readthedocs.org/en/latest/user-context.html#returning-the-user-context-hash to explain that when using symfony, you should look at the doc for the bundle.

Also, we should note that whereas the lib docs have `user_context_hash.php` as URL, our Symfony docs assume `user-context-hash` (when adding the route). Of course, the Varnish config should then also be changed to `user-context-hash` when using it with Symfony.

**Comment by ericvincenterv** [comment]
The docs state the following route : 
```` yaml
user_context_hash:
    path: /user-context-hash
````
Unless I am wrong the Varnish config should then be changed to "user-context-hash" and not "user_context_hash" when using it with Symfony

**Comment by ddeboer** [comment]
You’re right. I edited my post above so I won’t make the same mistake again. :wink:

**Comment by ddeboer** [comment]
See also https://github.com/FriendsOfSymfony/FOSHttpCache/issues/165.

**Comment by dbu** [comment]
once https://github.com/FriendsOfSymfony/FOSHttpCache/pull/168 is merged, this should be doable. the only BC way is `/_fos_user_context_hash`
