### ISSUE TITLE
fix naming of event listeners

### ISSUE THREAD

**Issue by dbu** [FriendsOfSymfony/FOSHttpCacheBundle#190]
we provide a couple of event listeners: https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/tree/master/EventListener

according to naming convention, those [should end with the word listener](http://symfony.com/doc/2.3/cookbook/bundles/best_practices.html#classes), not subscriber. they do implement the event subscriber interface, but their purpose is to be event listeners.

i suggest we do that when we get ready for a version 2 - its not that important and its a BC break for people extending the classes or doing things with the services.

**Comment by ddeboer** [comment]
For the sake of some history, see #46. :) But I agree, let’s follow Symfony standards here.

**Comment by dbu** [comment]
i know its my fault. i was thinking that when the interface says subscriber our thing is a subscriber too, but in this case the naming convention really makes more sense.

**Comment by dbu** [comment]
also while we break things there, we should probably switch to OptionsResolver for the optional constructor arguments

**Comment by ddeboer** [comment]
Also changed in the library: https://github.com/FriendsOfSymfony/FOSHttpCache/pull/324.
