### ISSUE TITLE
Use trait for EventDispatchingHttpCache from library

### ISSUE THREAD

**Issue by ddeboer** [FriendsOfSymfony/FOSHttpCacheBundle#192]
Currently we say [in our docs](http://foshttpcachebundle.readthedocs.org/en/latest/features/symfony-http-cache.html#extending-the-correct-httpcache):

> If your class already needs to extend a different class, simply copy the event handling code from the EventDispatchingHttpCache into your AppCache class. The drawback is that you need to manually check whether you need to adjust your AppCache each time you update the FOSHttpCache library.

Would it help to provide the re-usable code in a trait instead, so multiple inheritance becomes possible for (PHP 5.4+) users?

**Comment by dbu** [comment]
hm. first it would mean that *we* have to manually synchronize - unless we drop php 5.3 support which i propose to wait with until symfony 3.0 is here which will drop it.

i am not too sure how well it will work then either, because we have to raise events before and after some methods. this would go into AOP which is really not standard for symfony.

**Comment by ddeboer** [comment]
Yeah, this only makes sense when we can drop 5.3 support. We’ll need to experiment a bit to see whether it pays off to introduce a trait. I expect we can at least reduce the amount of code users have to copy into their AppCache class.

**Comment by dbu** [comment]
i labelled this v2 now - guess version 2 should drop php 5.3 support.

**Comment by dbu** [comment]
actually we should do that in the library. created https://github.com/FriendsOfSymfony/FOSHttpCache/issues/191

what remains to be done for the bundle is adapt documentation and maybe provide a default class using that trait, if we think that helps.

**Comment by dbu** [comment]
the trait is now in FOSHttpCache. what remains to be done is update the documentation and remove the kernel here.

**Comment by dbu** [comment]
all cache kernel code is now in the library.
