### ISSUE TITLE
Update inline C

### ISSUE THREAD

**Issue by ddeboer** [FriendsOfSymfony/FOSHttpCacheBundle#219]
The C snippet in the [docs](http://foshttpcachebundle.readthedocs.org/en/latest/reference/configuration/headers.html) needs updating along the lines of https://gitlab.com/dbu/varnish-workshop/merge_requests/8.

**Comment by dbu** [comment]
adding this to the library with tests: https://github.com/FriendsOfSymfony/FOSHttpCache/pull/214

once merged, we should remove this from the bundle 2.0 doc and refer to the library instead.

**Comment by ddeboer** [comment]
Inline C has been moved to the library and will be removed from the bundle in #235.
