### ISSUE TITLE
Invalidate Tag immediately instead of when command finishes

### ISSUE THREAD

**Issue by stevenmusumeche** [FriendsOfSymfony/FOSHttpCacheBundle#228]
I have a long running process that invalidates tags in Varnish.  I noticed that the tags seem to be accumulated and sent all at once when the command ends.  Since I need this task to run for hours, Is there a way to invalidate the tags immediately when the `invalidateTags` command is called?

**Comment by dbu** [comment]
i created https://github.com/FriendsOfSymfony/FOSHttpCache/pull/219 to better explain the invalidateTags method. you need to inject/fetch the CacheManager service and call `flush` after invalidating tags. this will trigger the invalidation requests immediately and should clear the list of tags to invalidate at the same time.

please check if things work as expected, i am not aware of other people having used invalidation in long running processes.

**Comment by stevenmusumeche** [comment]
I ran it through the debugger and it works as expected.  The tags are sent to varnish and the queue is cleared.
