### ISSUE TITLE
sanity check in invalidate:path command

### ISSUE THREAD

**Issue by dbu** [FriendsOfSymfony/FOSHttpCacheBundle#232]
i had a collegue trying to run `app/console fos:httpcache:invalidate:path ^/.*` which of course did nothing, but gave no error. made me wonder if we should scan the path for `*` and maybe `^` as first character and in those cases output a warning that paths do not support wildcards. its a bit messy but could be helpful in real world situations. wdyt @ddeboer ?

**Comment by ddeboer** [comment]
Makes sense.

Should we do this for the command only or also when calling `invalidatePath` on the CacheInvalidator? In the latter case, it should be a very light check, as we don’t want to slow down calls to that method too much.

**Comment by dbu** [comment]
i would hope developers look at the phpdoc a little bit when coding, so
they should notice. and if they don't they won't look at the logfile
probably. so i would only do it in the command.

**Comment by ddeboer** [comment]
We could also validate the path (following [RFC 3986](https://tools.ietf.org/html/rfc3986#section-2)) and throw a more generic exception if the path contains invalid characters, such as `^`. I’m not sure what our current default behaviour is however. If we URI-encode paths automatically, throwing an exception instead will be confusing.

**Comment by dbu** [comment]
well, we are moving to 2.0 which is a good moment for BC breaks :-)

i am not sure who's job it is to uri encode, the caller or FOSHttpCache. but for the regular expressoin based calls, it needs to be the caller that makes sure paths he wants to match are properly encoded (e.g. %20 and not space), so asking it for purge/refresh as well seems sensible to me. so we would check if the path is valid and throw an exception instead. if its not valid we could check for `^` and `.*` in order to give some extra hints.

**Comment by ddeboer** [comment]
As we rely on PSR-7, we should probably support [unencoded URIs too](http://www.php-fig.org/psr/psr-7/#psrhttpmessageuriinterface):

> Users can provide both encoded and decoded path characters.
> Implementations ensure the correct encoding as outlined in getPath().

**Comment by dbu** [comment]
do we need to do that handling? is it not the job of the PSR-7 implementation?

**Comment by ddeboer** [comment]
Yes, exactly, so we shouldn’t throw exceptions when purge/refresh is called with an unencoded URI.

**Comment by dbu** [comment]
ah, ok re-read the discussion above. so the only thing would be to check for * and ^ and maybe [] and () to warn that path is not about regular expressions? and let the psr-7 implementation handle everything else...

**Comment by ddeboer** [comment]
Correct.
