### ISSUE TITLE
Fatal error: Cannot redeclare class Symfony\Component\EventDispatcher\Event in POST requests

### ISSUE THREAD

**Issue by naitsirch** [FriendsOfSymfony/FOSHttpCacheBundle#242]
Since I have installed FOSHttpCacheBundle I get a strange error on POST requests (when submitting any form): 
```
Fatal error: Cannot redeclare class Symfony\Component\EventDispatcher\Event in C:\projects\acme\app\cache\dev\classes.php on line 2136

Call Stack:
    0.0020     136568   1. {main}() C:\projects\acme\web\app_dev.php:0
    0.0380    1908496   2. FOS\HttpCacheBundle\SymfonyCache\EventDispatchingHttpCache->handle() C:\projects\acme\web\app_dev.php:34
    0.0380    1908952   3. Symfony\Component\HttpKernel\HttpCache\HttpCache->handle() C:\projects\acme\vendor\friendsofsymfony\http-cache-bundle\SymfonyCache\EventDispatchingHttpCache.php:122
    0.0390    1928528   4. FOS\HttpCacheBundle\SymfonyCache\EventDispatchingHttpCache->invalidate() C:\projects\acme\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpCache\HttpCache.php:206
    0.0410    1948712   5. Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate() C:\projects\acme\vendor\friendsofsymfony\http-cache-bundle\SymfonyCache\EventDispatchingHttpCache.php:161
    0.0410    1948736   6. Symfony\Component\HttpKernel\HttpCache\HttpCache->pass() C:\projects\acme\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpCache\HttpCache.php:275
    0.0410    1949016   7. Symfony\Bundle\FrameworkBundle\HttpCache\HttpCache->forward() C:\projects\acme\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpCache\HttpCache.php:258
    0.0410    1949176   8. Symfony\Component\HttpKernel\Kernel->boot() C:\projects\acme\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\HttpCache\HttpCache.php:56
    0.0410    1949240   9. Symfony\Component\HttpKernel\Kernel->doLoadClassCache() C:\projects\acme\app\bootstrap.php.cache:2408
    0.0430    2034240  10. Symfony\Component\ClassLoader\ClassCollectionLoader::load() C:\projects\acme\app\bootstrap.php.cache:2573
    0.1000    4173632  11. require_once('C:\projects\acme\app\cache\dev\classes.php') C:\projects\acme\vendor\symfony\symfony\src\Symfony\Component\ClassLoader\ClassCollectionLoader.php:91
```
Now, when I delete the cache folder via filesystem (**not** with app/console cache:clear) the next POST request works, but all next POST requests are failing again with the same error message.
But when I execute `app/console cache:clear` after removing the cache folder it seem to work on all requests.

I have already figured out that on POST requests the `Symfony\Component\EventDispatcher\Event` class is loaded via autoloading when an instance of `CacheEvent` is created in `FOS\HttpCacheBundle\SymfonyCache\EventDispatchingHttpCache::invalidate`. Later the Symfony HttpKernel boots and loads the class cache (the *classes.php* in the cache folder) which contains the Event class, too. This results in the mentioned redeclaration error.

What confuses me, is that the Event class is not compiled into classes.php when `app/console cache:clear` is executed after removing the cache folder.

Does anyone has a clue about this issue?

**Comment by dbu** [comment]
How does your `web/app.php` file look? mine starts like this:

```
use Symfony\Component\HttpFoundation\Request;

$loader = require_once __DIR__.'/../app/bootstrap.php.cache';

require_once __DIR__.'/../app/AppKernel.php';
```

could it be that you load the AppKernel before loading bootstrap.php.cache? or do something else before loading the bootstrap?

**Comment by stof** [comment]
@dbu it is not about ``app/bootstrap.php.cache``, but about ``app/cache/dev/classes.php``, which is loaded by ``$kernel->loadClassCache()`` (or something like that, I'm not sure about the method name), which loads the file generated based on classes that bundles are asking to aggregate together.

**Comment by naitsirch** [comment]
@dbu My `app.php` looks similar to yours. **stof** is right. The problem is the `classes.php` which is mentioned in my PRs.
And afaik this issue only occures if you are using Symfony's cache with cache invalidation enabled.

**Comment by dbu** [comment]
i did not know that thing even existed :-O

got it now. thanks for working on the fix!

**Comment by ddeboer** [comment]
@dbu This seems quite a nasty bug. Do you have any idea why our tests didn’t catch it?

**Comment by dbu** [comment]
because it has to do with caching, we probably dont trigger that case.

**Comment by dbu** [comment]
this will be fixed in https://github.com/FriendsOfSymfony/FOSHttpCache/pull/249

the workaround for now is to do a `class_exists('FOS\\HttpCache\\SymfonyCache\\CacheEvent')` at the beginning of AppKernel::handle, and in app/console if the console uses the class cache mechanism of the kernel.
