### ISSUE TITLE
Priority for ContextProviders

### ISSUE THREAD

**Issue by antoligy** [FriendsOfSymfony/FOSHttpCacheBundle#246]
It is not possible to replace or prioritise the order in which context providers are supplied, meaning that it is not currently possible to consistently remove or add headers to the existing context hash.

**Comment by stof** [comment]
What do you mean by "remove or add headers" ?

**Comment by antoligy** [comment]
Sorry, I meant parameters.

So my use case is that I am building for a site using https://github.com/ezsystems/ezpublish-kernel which supplies its own context provider, unfortunately that context provider supplies parameters which I need to reliably remove to maximise cache hit rate and to minimise cache generation time.

**Comment by antoligy** [comment]
:+1: PR merged
