### ISSUE TITLE
CacheControlSubscriber dies on non-string request attribute

### ISSUE THREAD

**Issue by teohhanhui** [FriendsOfSymfony/FOSHttpCacheBundle#249]
Because of symfony/symfony#16529

But is there anything that should be done in `CacheControlSubscriber` to avoid that case?

**Comment by teohhanhui** [comment]
More specifically, in my case it's dying when `_controller` attribute is a callable (when handling exception in [ExceptionListener of HttpKernel](https://github.com/symfony/symfony/blob/v2.7.6/src/Symfony/Component/HttpKernel/EventListener/ExceptionListener.php))

**Comment by dbu** [comment]
ups. that indeed looks like a symfony bug. i don't want to include a workaround for this in this bundle as its hopefully a temporary problem. (if that bug report gets declined as a non-issue, we can reconsider)

i think if you need a workaround for now, you could create your own RuleMatcher implementation and have it first check the response, then the request. an exception response is probably not cacheable so you should not get into the request match check at all: https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/Http/RuleMatcher.php#L57

you can change the `fos_http_cache.rule_matcher.class` parameter in your application to use your replacement class. (note that for the 2.0 version of this bundle, we will drop the class parameters as recommended by symfony and you will need a compiler pass instead. )

**Comment by teohhanhui** [comment]
@dbu
> an exception response is probably not cacheable so you should not get into the request match check at all

That's not being checked in CacheControlSubscriber. But I guess you are right. It makes no sense to add cache control directives for non-cacheable requests, as per https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/issues/69#issuecomment-118622271...

**Comment by dbu** [comment]
this depends on what you configure as cacheable, see https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/Http/RuleMatcher.php#L68-L78

**Comment by teohhanhui** [comment]
That is irrelevant because the `throw`ing code comes before that...

**Comment by dbu** [comment]
yes, as said:

> i think if you need a workaround for now, you could create your own RuleMatcher implementation  and have it first check the response, then the request. an exception response is probably not  cacheable so you should not get into the request match check at all: https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/Http/RuleMatcher.php#L57

> you can change the fos_http_cache.rule_matcher.class parameter in your application to use your replacement class. (note that for the 2.0 version of this bundle, we will drop the class parameters as recommended by symfony and you will need a compiler pass instead. )

**Comment by teohhanhui** [comment]
Uhh... Thanks for the clarification. Now I get what you meant...

**Comment by ddeboer** [comment]
Is there anything we can do about this issue in this bundle?

**Comment by dbu** [comment]
it did not come up again, and i feel its a symfony responsibility to fix it if there is something broken. we don't provide any RequestMatcher implementations in this bundle.
