### ISSUE TITLE
Dynamic base_url

### ISSUE THREAD

**Issue by benr77** [FriendsOfSymfony/FOSHttpCacheBundle#251]
Is it possible to define a dynamic base_url parameter for the proxy_cache?

I have a SaaS application that has each account on a subdomain but a single codebase. So to get the proxy host correctly I need SUBDOMAIN.myhost.com but cannot hard code this in to the configuration.

I've tried Symfony's expression language to call a service but it does not seem to be working

`base_url: @=service('site_manager').getAccount() ~ '.' ~ %base_host%`

Is there a was to intercept the base_url parameter and redefine it on each request perhaps?

Thanks

**Comment by dbu** [comment]
is expression language evaluated for the parameter at all? if so, your question might better be asked in a general symfony channel.
if all else fails, you could do your own proxy client wraps the varnish (or whichever you use) client and gets injected the site manager service to properly set up the proxy client.

**Comment by benr77** [comment]
Yes, as it turns out the expression language is ignored as parameters are fixed once the cache is built so anything dynamic is forbidden. Expression language of course still good for DI definitions which are evaluated at runtime.

I have done exactly has you suggest - created a proxy to wrap the Symfony HttpCache client and define the base host accordingly.

```
<?php

namespace MyApp\ProxyClient;

use MyApp\DependencyInjection\SiteManagerService;
use FOS\HttpCache\ProxyClient\Symfony;

/**
 * Symfony HttpCache invalidator.
 */
class MyAppProxyClient extends Symfony
{
	/**
	 * {@inheritDoc}
	 *
	 * @param array       $servers     The servers parameter - i.e. the list of caching proxies - from the fos_cache configuration
	 * @param SiteManager $siteManager The SiteManager service which can provide the SaaS subdomain string
	 * @param string      $baseHost    MyApp parameter holding fixed portion of domain name
	 */
	public function __construct(array $servers, SiteManager $siteManager, $baseHost)
	{
		if ($siteManager->getSaasAccount()) // Ignore if no SaaS account available
		{
			$baseUrl = $siteManager->getSaasAccount()->getAccount() . '.' . $baseHost;
			parent::__construct($servers, $baseUrl);
		}
	}
}
```

This appears to work just fine, and is simple enough for my liking. Easy enough to extend for Varnish too if needed.

I have omitted some of the optional constructor arguments and this does not seem to have had an effect.

Thanks for your suggestion.
