### ISSUE TITLE
Configurable ExpressionLanguage class

### ISSUE THREAD

**Issue by wickedOne** [FriendsOfSymfony/FOSHttpCacheBundle#252]
It would be nice to be able to define your own ``ExpressionLanguage`` class.
This would enable additional / custom functionality for tagging with configuration rules.

**Comment by dbu** [comment]
i just had a look and it seems TagSubscriber and InvalidationSubscriber
already accept the expression language as second argument. however,
there is no way to configure this at the moment.

i would be happy if you can do a pull request that allows to configure a
service for the expression languague instance to use with each of those
services. do you think you can do that?

the pull request should have the Configuration class update and
FOSHttpCacheExtension handling it (probably in the service definition
just do invalid=ignore to keep things simple). as well tests and a bit
of documentation (link to the relevant symfony doc pages for the details
of expression language and defining it as a service)

**Comment by wickedOne** [comment]
yes, i'll have a go at that later this week

do you prefer the class definition under the ``tag`` node in the configuration or under the ``cache_manager`` like the ``custom_proxy_client`` option?

**Comment by dbu** [comment]
i think for the TagSubscriber, it should be in the `tags` section. above
the `rules`. and for InvalidationSubscriber in the `invalidation` section.

that way its next to the place where regular expressions are placed in
the configuration. does that make sense to you?

**Comment by wickedOne** [comment]
yes makes perfect sense, thans for the quick reply!
