### ISSUE TITLE
Disable functionality via .yml configuration

### ISSUE THREAD

**Issue by benr77** [FriendsOfSymfony/FOSHttpCacheBundle#259]
I'm trying to disable the functionality of this bundle for my test environment.

So I have all my cache control rules, and invalidation rules etc set up in config.yml. All works as expected.

If I then add `fos_http_cache: ~` in to my config_test.yml file, to override any config from the main config.yml file, this *does* disable the caching of various pages etc, but it *does not* appear to disable the invalidation rules. I am still seeing PURGE requests in my web server log.

I'm wondering if this is something to do with the use of `cannotBeOverwritten()` [here](https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/DependencyInjection/Configuration.php#L251)

If I try the following I get an error message _"Invalid configuration for path "fos_http_cache": You need to enable the cache_manager and invalidation to use rules."_

```
fos_http_cache:
  cache_manager:
    enabled: false
  invalidation:
    enabled: false
    rules: ~
```

Is there something I'm missing or is this potentially a bug in the configuration?

Thanks

**Comment by dbu** [comment]
hm, i honestly do not know why we have the `cannotBeOverwritten` in there. the git blame just shows that i moved that around last year... i remember from other complex configurations that it can get rather complicated when overwriting lists of things (you would append rather than replace i think). if you want to experiment with the effects of removing that line, please do and if you are conclusive what it does and does not, do a PR.

the alternative option would be to move the configuration out of config.yml and have a dedicated fos_http_cache.yml (or whatever you want to call it) and include that file from config_dev and config_prod only.

**Comment by benr77** [comment]
I have tried moving the config out in to a `fos_cache.yml` and including as required instead of by default. This works just fine.

Removing the `cannotBeOverwritten` has no effect at all from my testing. It does not seem possible to remove invalidation rules that have already been defined. But then also it looks like you cannot disable the invalidation once rules are defined.

Looking at the bundle configuration, I'm curious about the initial validation rules on line 96-99:

```
->validate()
    ->ifTrue(function ($v) {return $v['invalidation']['rules'] && !$v['invalidation']['enabled'];})
    ->thenInvalid('You need to enable the cache_manager and invalidation to use rules.')
    ->end()
```

This is telling me that if of course I need to enable the invalidation in order to use the invalidation rules - but the invalidation section is enabled automatically when configuring the cache manager so normally this would not be triggered.

But this rule also tells me that I cannot disable the invalidation functionality if I have already defined any rules. Surely it should be possible to simply turn off the invalidation functionality regardless of the rest of the invalidation configuration simply by specifying `invalidation: enabled: false`

Anyway, food for thought but no need to make any changes as the workaround of moving config to `fos_cache.yml` is easy enough.

**Comment by dbu** [comment]
hm. yes, i think we where a bit over-eager there. we do want it for the places where you could enable the cache manager without enabling invalidation, but in this case it looks like by default, things will work fine and we should allow the use case.

@ddeboer do you agree? @benr77 do you want to create a pull request that just removes this line of validation?

**Comment by ddeboer** [comment]
Yes. As long as adding rules sets `enabled: true` automatically (as it is now) I agree that users should be able to override and set it to `false`.

**Comment by benr77** [comment]
Ok, will create a PR for this soon as I get a chance later. 

Also, the block of validation immediately above the one we are talking about looks like an identical check but for tagging instead of invalidation. Shall I create a PR for removing this as well because it's going to be the same issue here is it not?

**Comment by dbu** [comment]
indeed, that looks like the same logic applies there. please do the PR in one go, its fixing the same logic error that occurs twice :-)
