### ISSUE TITLE
Using a service inside a custom proxy client

### ISSUE THREAD

**Issue by benr77** [FriendsOfSymfony/FOSHttpCacheBundle#264]
I'm using a custom proxy client class. It's defined as a service, and I inject a SiteManager service in to it.

The SiteManager service is populated by an event listener on kernel.request and console.command events, which provide it with parameters needed to build a URL.

The problem is that the Proxy Client constructor is executed BEFORE the event listener, so my SiteManager class has no data. (the event listener has a high priority value, but this makes no difference).

How can I ensure that the Proxy Client is only instantiated after the event listener has finished? Do I need a compiler pass or something?

Thank you

**Comment by dbu** [comment]
proxy client should be instantiated at the point when something needs the CacheManager i think. to debug, you could try to put a breakpoint in the proxy client constructor (or simply throw an exception) and look at the call stack to try to see at which point this is triggered. reading the app/cache container class at the indicated lines should also tell what is depending on the client and triggers the instantiation.
