### ISSUE TITLE
include request object in match_response

### ISSUE THREAD

**Issue by wickedOne** [FriendsOfSymfony/FOSHttpCacheBundle#270]
would it be ok for me to add the request object in the ``match_response`` evaluation in the [RuleMatcher](https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/Http/RuleMatcher.php#L62-L64)?

i'm currently working on an api which returns a ``201`` response code for successful ``PUT`` requests.
cleary i don't want to add the ``201`` to the ``additional_cacheable_status``, so when adding the request to the evaluation i could do something like:
```yaml
match_response: response.getStatusCode() == 201 & request.getMethod() == 'PUT'
```

**Comment by ddeboer** [comment]
What you want is already possible, as described by @dbu in https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/pull/272#discussion_r49164808. :wink:
