### ISSUE TITLE
User Context with Symfony built-in cache, private or public cache?

### ISSUE THREAD

**Issue by pasdeloup** [FriendsOfSymfony/FOSHttpCacheBundle#285]
Hi,

I spent some time trying to understand how to make User Context cache work with Symfony built-in cache, and still don't get it. Documentation could be improved.

First there is an ambiguity between the bundle and the library: the bundle installation page has links to the library for details, so by following it, I added my Client Context subscriber in my AppCache class, and at the same time the bundle also seems to do it automatically when adding the configuration so pre_handle was called twice, and triggered a security alert.

Second problem, that I couldn't solve, is that I couldn't understand which cache settings I should use for my controller.
Using @Cache(public=true,maxage=60)
The cache is working but public, so it doesn't check User Context
Using @Cache(public=false,maxage=60)
The cache is not working, it misses all the time because  isCacheable() is false.

Thanks.

**Comment by dbu** [comment]
@lolautruche can you maybe help here?

@pasdeloup which versions of the library and of the bundle are you using? it might be that the documentation cross-linking confuses between the stable 1.3 branch and the master version that is in development.

**Comment by lolautruche** [comment]
Hi

You should check the slides of our talk about it: http://lolautruche.github.io/ez/going-crazy-with-caching.html#/3/4 (press down arrow for more diagrams).

Regarding your cache settings in your controller, you **must** set the cache public.

**Comment by pasdeloup** [comment]
Thanks David.
I'm using bundle version v1.3.6 and library v1.4.2. Should I switch to Master?

Thanks Jérôme.
I'll check those slides.

**Comment by dbu** [comment]
> I'm using bundle version v1.3.6 and library v1.4.2. Should I switch to

i would not. i was mainly wondering if the documentation got mixed up
between stable and latest. latest is about the 2.x versions and might be
inaccurate or incompatible with the 1.x code.

**Comment by pasdeloup** [comment]
Thanks,  now it starts to be working: _fos_user_context_hash was not correctly passing security so all my users had the same hash  :(

However, for the cache public, it's in contradiction with the latest documentation (maybe a feature not yet available in the stable version?)

> You do not want intermediary proxies to cache responses that depend on the context. If the client will not see a difference when his context changes (e.g. is removed from or added to groups on server side), you also do not want the clients to cache pages. Because VARY is used for the control of the caching proxy, it is not available to control clients. Often, **the best solution is to mark your pages as private** with a max-age of 0 and use the custom TTL mechanism (see the documentation for Varnish or the Symfony HttpCache).

Is there a way to keep the cache private from the client point of view but shared for the Symfony HttpCache?

**Comment by dbu** [comment]
okay, sorry for that one. i think the documentation we added there makes no sense. marking the page private will indeed prevent caching. what you want to do is set `s-maxage=0` and add a header for custom ttl as explained in http://foshttpcachebundle.readthedocs.org/en/stable/reference/configuration/headers.html#reverse-proxy-ttl

that way, the symfony cache will get a non-zero ttl, while all other caches will not cache the page. i created https://github.com/FriendsOfSymfony/FOSHttpCache/pull/278 to adress this mistake in the FOSHttpCache documentation. does that make sense to you? if not, please comment on the pull request directly.
