### ISSUE TITLE
Invalidate cache with User Context.

### ISSUE THREAD

**Issue by Gu3** [FriendsOfSymfony/FOSHttpCacheBundle#292]
Hi everybody ! 
My project : X people, X organizations, X pages. Each people can have access to one or more organiztions. Each organizations have access to one or more pages. Each people can have one or more roles who can view and/or create and/or edit one or more page.

Example : User A (admin), in organization 498 see all fields of page people
                 User B (member), in organization 498 see just few fields of page people
                 User C (member), in organization 500 see all fields of page people
                 
So I need to have a cache for each people, in each organization for each pages. 

I use Varnish, with an user context and my own Hash and I put an extra parameter on response 'X-Organization' because I need to invalidate my cache (on Post/Put/Delete) based on the current organization where the user is connected.

So I test Purge, but when I do : 
$this->cacheManager->invalidatePath('/api/people',array('X-Organization' => '498'))->flush();
All pages 'api/people' were invalidate, for all Organizations :: cache is invalidate for user A,B,C instead of user A and B

So I test with a Ban : 
$this->cacheManager->invalidate(array('X-Url' => '/api/people', 'X-Organization' => '498'))->flush();
None page was invalidate...

default.vcl
```
sub vcl_recv {
    # Happens before we check if we have this in cache already.
    #
    # Typically you clean up the request here, removing cookies you don't need,
    # rewriting the request, etc.

    if (req.method == "PURGE") {
        if (!client.ip ~ invalidators) {
            return (synth(405, "Not allowed"));
        }
        return (purge);
    }

    if (req.method == "BAN") {
        if (!client.ip ~ invalidators) {
            return (synth(405, "Not allowed"));
        }

        if (req.http.X-Cache-Tags) {
            ban("obj.http.X-Host ~ " + req.http.X-Host
                + " && obj.http.X-Url ~ " + req.http.X-Url
                + " && obj.http.content-type ~ " + req.http.X-Content-Type
                + " && obj.http.X-Cache-Tags ~ " + req.http.X-Cache-Tags
            );
        } else {
            ban("obj.http.X-Host ~ " + req.http.X-Host
                + " && obj.http.X-Url ~ " + req.http.X-Url
                + " && obj.http.content-type ~ " + req.http.X-Content-Type
                + " && obj.http.X-Organization ~ " + req.http.X-Organization
            );
        }

        return (synth(200, "Banned"));
    }

    if(req.http.Authorization){
       set req.http.OT-Authorization = req.http.Authorization;
       unset req.http.Authorization;
    }

    # Prevent tampering attacks on the hash mechanism
    if (req.restarts == 0
        && (req.http.accept ~ "application/vnd.fos.user-context-hash"
            || req.http.X-User-Context-Hash
        )
    ) {
        return (synth(400));
    }

 # Lookup the context hash if there are credentials on the request
    # Only do this for cacheable requests. Returning a hash lookup discards the request body.
    # https://www.varnish-cache.org/trac/ticket/652
    if (req.restarts == 0
        && (req.http.cookie || req.http.OT-Authorization)
        && (req.method == "GET" || req.method == "HEAD")
    ) {
        # Backup accept header, if set
        if (req.http.accept) {
            set req.http.X-Fos-Original-Accept = req.http.accept;
        }
        set req.http.accept = "application/vnd.fos.user-context-hash";

        # Backup original URL
        set req.http.X-Fos-Original-Url = req.url;
        set req.url = "/_fos_user_context_hash";

        # Force the lookup, the backend must tell not to cache or vary on all
        # headers that are used to build the hash.
        return (hash);
    }

# Rebuild the original request which now has the hash.
    if (req.restarts > 0
        && req.http.accept == "application/vnd.fos.user-context-hash"
    ) {
        set req.url = req.http.X-Fos-Original-Url;
        unset req.http.X-Fos-Original-Url;
        if (req.http.X-Fos-Original-Accept) {
            set req.http.accept = req.http.X-Fos-Original-Accept;
            unset req.http.X-Fos-Original-Accept;
        } else {
            # If accept header was not set in original request, remove the header here.
            unset req.http.accept;
        }

        # Force the lookup, the backend must tell not to cache or vary on the
        # user hash to properly separate cached data.
        return (hash);
    }
}

sub vcl_backend_fetch {
   if(bereq.http.OT-Authorization){
      set bereq.http.Authorization = bereq.http.OT-Authorization;
      unset bereq.http.OT-Authorization;
   }
}

sub vcl_backend_response {
    # Happens after we have read the response headers from the backend.
    #
    # Here you clean the response headers, removing silly Set-Cookie headers
    # and other mistakes your backend does.

    set bereq.http.OT-Authorization = bereq.http.Authorization;
    unset bereq.http.Authorization;

    if (bereq.http.accept ~ "application/vnd.fos.user-context-hash"
        && beresp.status >= 500
    ) {
        return (abandon);
    }
}

sub vcl_deliver {
    # Happens when we have all the pieces we need, and are about to send the
    # response to the client.
    #
    # You can do accounting or modifying the final object here.

    # On receiving the hash response, copy the hash header to the original
    # request and restart.
    if (req.restarts == 0
        && resp.http.content-type ~ "application/vnd.fos.user-context-hash"
    ) {
        set req.http.X-User-Context-Hash = resp.http.X-User-Context-Hash;
        set req.http.X-Organization = resp.http.X-Organization;
        return (restart);
    }

    # If we get here, this is a real response that gets sent to the client.

    # Remove the vary on context user hash, this is nothing public. Keep all
    # other vary headers.
    set resp.http.Vary = regsub(resp.http.Vary, "(?i),? *X-User-Context-Hash *", "");
    set resp.http.Vary = regsub(resp.http.Vary, "^, *", "");
    if (resp.http.Vary == "") {
        unset resp.http.Vary;
    }

    # Sanity check to prevent ever exposing the hash to a client.
    unset resp.http.X-User-Context-Hash;
}

```

My hash provider : 

```
public function onKernelResponse(FilterResponseEvent $event)
    {
        $response = $event->getResponse();
        $request = $event->getRequest();

        //Need that if we want flush the right path with Varnish...
        if ($request->get('_route') === 'user_context_hash' ) {
            $response->headers->add(['X-Organization' => $this->accessService->getAccess()->getOrganization()->getId()]);
        }
        $response->setVary('X-Organization');
    }
```

After Post/Update/Delete : 

```
//BAN
$this->cacheManager->invalidatePath('/api/people',array('X-Organization' => '498'))->flush();
OR
//Purge
$this->cacheManager->invalidate(array('X-Organization' => '498'))->flush();
```

My ban list : 

`1460646798.587354     1    obj.http.X-Host ~ .* && obj.http.X-Url ~ .* && obj.http.content-type ~ .* && obj.http.X-Organization ~ 498`

Any Ideas ? 
Cheers ! 

Vincent. 

Sorry for the book ! (and for the approximate english too!)

**Comment by dbu** [comment]
interesting use case, i have to remember this one for the next talk on the user context :-)

invalidatePath / PURGE indeed does not work, as it operates on specific urls and invalidates every variant of that url. what you want is indeed BAN. 

looking at your vcl, i don't see what would be wrong. i realize that the ban seems to get added correctly to the ban list. the only idea i have is to verify if your answers really have the headers you expect. and using varnishlog locally to make sure your assumptions as to when something was cached or not cached are correct. i tend to also use wireshark to be sure i see what is going on in my network.

**Comment by Gu3** [comment]
Hi ! 
Thanks for the answer ! 
I found a solution : I change my ban Rule : 

```
ban(
                "req.http.Host ~ " + req.http.Host
              + " && req.http.X-Url ~ " + req.http.X-Url
              +  " && req.http.X-Ot-Organization ~ " + req.http.X-Ot-Organization
            );
```

instead of : 

```
ban("obj.http.X-Host ~ " + req.http.X-Host
                + " && obj.http.X-Url ~ " + req.http.X-Url
                + " && obj.http.content-type ~ " + req.http.X-Content-Type
                + " && obj.http.X-Organization ~ " + req.http.X-Organization
            );
```

I check my req instead of my obj.

Cheers, 

Vincent.

**Comment by dbu** [comment]
oh well, right. VCL can sometimes be non-obvious to read. thanks for the update.

**Comment by hardik8585** [comment]
HI 
I am also facing similar issue. 

Not working ban,
ban obj.http.X-VCL-Company-ID ~ abc  && obj.http.X-VCL-Host ~ testUrl.com  && obj.http.X-VCL-Path ~ /bigsize.jpg\\?x-ioa-image-q=20

Working ban (above and below both same except query string is eliminated and its working)
ban obj.http.X-VCL-Company-ID ~ abc  && obj.http.X-VCL-Host ~ testUrl.com && obj.http.X-VCL-Path ~ /bigsize.jpg

working,( if i am using query string than have to use req.url inplace of obj.http)
ban obj.http.X-VCL-Company-ID ~ abc  && obj.http.X-VCL-Host ~ testUrl.com && req.url ~ /bigsize.jpg\\?x-ioa-image-q=20

question is, why with query string first ban request is not working but 3rd is working fine ? I stuck here and not able to decide which have to use ?

Thank you..!

**Comment by dbu** [comment]
are you sure you copied the req.url of the original request to obj.http.X-VCL-PATH? otherwise i can't think why it would not work. best ask the varnish people, as this seems not related to this bundle but to VCL itself.

**Comment by hardik8585** [comment]
Hi

Thank you. I end up in using obj.http.X-VCL-URL in place of
obj.http.X-VCL-PATH.

One more think want to know.

For ban with query string I used like \? and its working fine. like \?x=10
Now one more requirement came, purge url may contain & (\?x=10&y=20) which
is again not accepting by varnish and looks like have to escaped ?
Is there any list of characters need to be escaped if you can share across.

Thank you
Hardik

**Comment by dbu** [comment]
afaik they use normal regular expressions apart from not needing to escape forward slashes. https://docs.fastly.com/guides/vcl/vcl-regular-expression-cheat-sheet

best have a look at a regular expressions reference to see which characters need escaping.
