### ISSUE TITLE
lack of interfaces for CacheManager & TagHandler

### ISSUE THREAD

**Issue by gsdevme** [FriendsOfSymfony/FOSHttpCacheBundle#293]
I want to create a no-operation version of the CacheManager and TagHandler for when my application is not behind a reverse proxy.

**Issues**
1. We want to have our deployments run `fos:httpcache:invalidate:regex` for example but if we deploy to a environment without a varnish & varnish configured the command will fail with 
```
  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  You have requested a non-existent service "fos_http_cache.cache_manager".
```
2. Similar situation with the `TagHandler`, if the tags are disabled the service `fos_http_cache.handler.tag_handler` won't be registered therefore our container build fails.

**Solutions**
1. Provider interfaces for both the Taghandler & CacheManager which would allow application vendors to create a no operation service (that or include this no operation code within this bundle).
2. Allow the commands to fail siliently without the `fos_http_cache.cache_manager` which would help issue 1. 
3. Leave this problem to the application vendor, they should use compiler passes and not rely on the `CacheManager` and `TagHandler` always existing within the container.
4. Provide a Noop client? https://github.com/FriendsOfSymfony/FOSHttpCache/tree/master/src/ProxyClient

I'd be happy to know opinions here if you are interested in #1 Im happy to create a PR? If this is not a problem you want to solve in this bundle then fair enough close :)

**Comment by dbu** [comment]
your scenario makes sense, and we should support it. i think i like option 4 best. then you could configure FOSHttpCache to use the noop client. this gives the most consistent behaviour, even at the cost of a slight overhead versus a cache manager that itself is a noop.

1 having interfaces seems a lot when the only use case i see is yours, and would still need compiler passes. it would be my second choice after 4. no-op flags to the manager feel wrong. 2 sounds dangerous as it can hide errors. 3 is not developer friendly and promotes bad design with "optional dependencies".

do you want to do a pull request for option 4 to add such a noop client to FOSHttpCache and configuration for it to FOSHttpCacheBundle?

**Comment by dbu** [comment]
fixed in https://github.com/FriendsOfSymfony/FOSHttpCache/issues/289
