### ISSUE TITLE
Avoid storing the hash generation route as last-visited-url

### ISSUE THREAD

**Issue by gggeek** [FriendsOfSymfony/FOSHttpCacheBundle#302]
It _sometimes_ happens that the hash generation route is stored as last visited url when the user is logging in.
When this happens, the user gets redirected to the hash_generation route upon login. And debugging the reason for that is not easy.

The theory behind this problem is that it is due to some misconfiguration, eg. the hash gen route not being accessible to anon users. But there is no clear consensus about the exact range/type of misconfigurations which could be involved.

It would be nice if, when this type of situation is happening:
- users would not be redirected to the hash gen route, but to their intended post-login url
- a warning message be logged

One way to make this happen is via a custom access exception listener, but other solutions could do as well.

The problem is discussed at length at https://github.com/FriendsOfSymfony/FOSHttpCache/issues/287

**Comment by gggeek** [comment]
PS: sorry for spamming 3 issue trackers with the same issue. I am not sure where the best place to apply a fix will be...

**Comment by dbu** [comment]
we could provide a customized listener that avoids ever storing the hash lookup url as last visited. or we could define the hash lookup route to redirect to the homepage in case that the request is not made with the appropriate headers, which means the hash listener does not trigger.

but i still strongly doubt that you will end up with a working system if the hash lookup url can not be accessed by some users so i doubt it makes much sense. if you want to do a PR, i suggest that you add to the documentation in http://foshttpcachebundle.readthedocs.io/en/latest/features/user-context.html#configuration where we explain how to define the lookup route and add the things to redirect to the homepage on that route, and the explanation that the hash lookup will answer before the redirect triggers.

**Comment by dbu** [comment]
is there anything we can do to further clarify this?
