### ISSUE TITLE
etag not sent to varnish

### ISSUE THREAD

**Issue by wideawake** [FriendsOfSymfony/FOSHttpCacheBundle#307]
Hi,

I have a problem with the etag header.

My Controller (which returns a View from FOSRestBundle) sets a not empty etag.
If I set in the response that it has to be cached then Varnish handles it right but doesn't send the etag with the response headers, nor it appears in varnishlog from the backend response.

Things change when I don't set caching headers in the response, Varnish will serve the response (not from cache) and etag is sent (not at the very first request).

Do you have any idea?

Thanks

**Comment by wideawake** [comment]
**UPDATE**
In dev env => etag is sent along with caching headers
In prod env => etag is missing

**Comment by wideawake** [comment]
maybe related to https://github.com/nulab/nginx-gzip-filter-allow-weak-etag-patch

checking on it...

**Comment by wideawake** [comment]
**SOLVED**
Setting the etag as wake make nginx preserve the etag, otherwise it removes the etag when gzip is enabled and the etag is not wake.

**Comment by dbu** [comment]
glad you solved it :-)

so this is an nginx specific issue? if you see a place in the documentation where we should mention this, please do a pull request on the documentation. maybe a note at the bottom of http://foshttpcachebundle.readthedocs.io/en/latest/features/headers.html ?

**Comment by wideawake** [comment]
I'm sorry dbu, but I have to re-open.

Setting wake etags makes nginx not removing them (tested disabling varnish).

With varnish enabled, etags are not sent. For now I'm disabling varnish while I investigate further.

**Comment by dbu** [comment]
the etag configuration option of FOSHttpCacheBundle does not generate
weak etags, only strong etags. if it helps, we could add an option for
generating weak etags. not sure how the rest of symfony handles them,
but hopefully varnish / nginx already do the etag handling.

apart from that, i assume this bundle can not do much about this, its a
question of your setup. maybe put an nginx in front of varnish that does
gzip (and ssl termination maybe). it makes little sense to duplicate
caches between gzip and non-gzip. or maybe just let varnish handle gzip
instead of nginx.

**Comment by wideawake** [comment]
Upgraded nginx from version 1.6.1 to the latest (info http://nginxlibrary.com/debian-latest-nginx/) and now varnish has the weak etags. **So it was nginx.**

Now all responses with _Cache-Control: public_ have **forced** wake tags, while  _Cache-Control: private_ have at the first request a wake tag, normal tag the next ones.

About your question: the response class of http foundation allow to set weak or strong etag.

**Comment by dbu** [comment]
great! anything left to do on this issue or can we close it?

**Comment by wideawake** [comment]
I think we can close, hopefully will help someone ;)
