### ISSUE TITLE
Feature: no-store header missing

### ISSUE THREAD

**Issue by xrow** [FriendsOfSymfony/FOSHttpCacheBundle#315]
Hello,

I wanted to add a no-store header . The problem was I got this message:

Unrecognized option "no_store" under "fos_http_cache.cache_control.rules.5.headers.cache_control"

I guess the feature si not implemented.

**Comment by dbu** [comment]
indeed, looking at https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/DependencyInjection/Configuration.php#L195-L204 it seems that no_store is missing there.

can you do a PR (from and against the 1.3 branch) to add it? please also add it in the documentation reference (Resources/doc/reference/configuration/headers.rst) and in the configuration test and the CacheControlSubscriberTest.php

**Comment by dbu** [comment]
ftr: this feature should not be added to the 1.3 branch but to the master branch. it could go into a 2.x release if you want to work on it @xrow

**Comment by pjuanda** [comment]
Hi @dbu, is there any particular reasons why this feature will not be added on 1.3 branch instead 2.x ?

**Comment by dbu** [comment]
the reason is that we are getting closer to release 2 and as its kindof a new feature it is better off in 2 than a patch release of 1.3. merging a change from 1.3 to master will also be harder now, as we did some refactorings in master.
