### ISSUE TITLE
Invalidate routes not working

### ISSUE THREAD

**Issue by Lionel09** [FriendsOfSymfony/FOSHttpCacheBundle#318]
Hi,

I'm just discovering all this "HTTP cache" stuff and I'm trying to do a first implementation of this bundle: setting a max-age for every routes and invalidate cache for all routes with an admin action.

I'm using Symfony 2.8 and the build-in Symfony Http Cache Proxy in a classical LAMP environnement.

I've tried with this config, but it doesn't seem to work. When I use an Http Request tool, I've always got this header until the s_maxage is reached:

> X-Symfony-Cache: GET /my-front-page: fresh

config.yml

    fos_http_cache:
        cache_control:
            defaults:
                overwrite: true
            rules:
                # match everything to set defaults
                -
                    match:
                        host: ^www.mywebsite.com$
                        path: ^/
                    headers:
                        cache_control: { public: true, max_age: 5, s_maxage: 60 }
    
        proxy_client:
            symfony:
                servers: 127.0.0.1
                base_url: www.mywebsite.com/

Admin action code:

    /**
     * Refresh HTTP cache
     */
    public function refreshCacheAction()
    {
        $cacheManager = $this->get('fos_http_cache.cache_manager');
    
        // Invalidate all front routes
        $cacheManager->invalidateRoute('Homepage');
    
        $contents = ContentQuery::create()->filterByOnline(true)->find();
        foreach($contents as $content) {
            $cacheManager->invalidateRoute('Content', array('id' => $content->getId())->flush();
        }
    
        $cacheManager->flush();
    
        return $this->redirect($this->generateUrl('AdminHomepage'));
    }

Did I miss something?
Note: all apologies if it's not the right place for this sort of newbie question, so i've posted it on [stackoverflow](http://stackoverflow.com/questions/40739057/invalidate-all-http-cache-with-symfony2) too.

**Comment by Lionel09** [comment]
I have made an error and the route was not invalidate: all works fine as expected.

**Comment by ddeboer** [comment]
Good to hear! :wink:
