### ISSUE TITLE
Depricated calls (Symfony 3.2.*)

### ISSUE THREAD

**Issue by jeireff** [FriendsOfSymfony/FOSHttpCacheBundle#343]
User Deprecated: Checking only for cacheable HTTP methods with Symfony\Component\HttpFoundation\Request::isMethodSafe() is deprecated since version 3.2 and will throw an exception in 4.0. Disable checking only for cacheable methods by calling the method with `false` as first argument or use the Request::isMethodCacheable() instead.

User Deprecated: Using a colon that is not followed by an indication character (i.e. " ", ",", "[", "]", "{", "}" is deprecated since version 3.2 and will throw a ParseException in 4.0.

**Comment by dbu** [comment]
this should be fixed in ddc8c148a91d40c2810181f276635e7962d13f38 . did you test with the current master? if you look at the 1.x releases, we can close this issue as those versions will never support symfony 4.

**Comment by dbu** [comment]
ping @jeireff

**Comment by jeireff** [comment]
Thank you for your help and fast answer and also for the "inline" fixes. I won't use them, cause my vendor should not be edited (to much different projects). And you was right, I'm at version 1.x, so thats the deal ;)

But at least I have problems with upgrading to dev master and I can't mention why.

**Comment by dbu** [comment]
i would not upgrade to dev-master yet, it will become 2.0 and is not yet stable. if you use version 1 with symfony 3.2, set your phpunit to ignore the deprecation warnings about this one.
