### ISSUE TITLE
Soft Purge

### ISSUE THREAD

**Issue by JonasHaouzi** [FriendsOfSymfony/FOSHttpCacheBundle#353]
Hello guys.

A big thank you to all the contributors of this bundle that helped us a lot. My turn to suggest some improvement and share them with you.

### Preamble
This bundle supports perfectly the cache invalidation through tags. In our case, the code we have first invalidate a page, and then, call it again to warm up its content and make it ready for the users. As already pointed out by others users, this opens a gate for _unlucky users_ that will wait for the new content to be fully loaded before getting the final output.

---

### The idea...
I did some research and I found an interesting vmod: [libvmod-xkey](https://github.com/varnish/libvmod-xkey)
It introduces a concept of _soft purging_, which set the TTL to 0 and let the _grace period_ work as expected in your VCL.

Meanwhile, forcing the generation of this page again (forcing by setting a specific header, for example) looks easily doable and will avoid some users (the _unlucky users_) to pay for the loading time.

---

We are planning to try this feature in our project in the next couple of weeks, and I was wondering if:
- some of you already had this issue?
- if not, if making it available for this bundle is something the community would like?

Thanks in advance.

**Comment by stof** [comment]
Support for xKey is a WIP in the FOSHttpCache library: https://github.com/FriendsOfSymfony/FOSHttpCache/pull/332

**Comment by JonasHaouzi** [comment]
Right, thanks!
