### ISSUE TITLE
Questioning the user context

### ISSUE THREAD

**Issue by Toflar** [FriendsOfSymfony/FOSHttpCacheBundle#357]
Hey guys,

I was wondering how much v2 is a thing already :-)
I did not know about this bundle, nor the library up until today and actually only found it by chance because I was looking for a solution to implement that "preflight request idea".
By "preflight request idea" I mean the extra request on `/_fos_user_context_hash` to then replicate the `X-User-Context-Hash` onto the real request.
It's a great concept, I just wonder why you are limiting it to user context hashing.
Let me tell you about my example: I have some legacy application that does provide two different page layouts, a desktop one and a mobile one. By setting a cookie, you can force one of the two variants so you already see the problem: I need to `Vary` on something like `Page-Layout: mobile` and `Page-Layout: desktop`.

All the user context listener does in my opinion is extracting information out of the `Cookie` (and/or `Authorization`) header and splitting it up in a `X-User-Context-Hash` header.

Is there any reason why you limited this? I mean, couldn't we have it way more generic?
I'll adjust the docs and rephrase it so you understand what I mean:

1. A client requests `/foo.php` (the original request).
2. The proxy server receives the request. If the request might contain user specific information (`Cookie` or `Authorization` headers) it sends a request (the preflight request) with a special accept header (`application/vnd.fos.replay_headers`) to a specific URL, e.g., `/_fos_replay_headers`.
3. The application receives the preflight request. The application knows the user specific information based on e.g. the `Cookie` header that maps to e.g. a PHP session and thus about things like user context (roles, permissions, etc.) and adds headers based on that information. The application then returns a response containing these headers plus the general header `FOS-Replay-Headers` that contains a list of all headers that should be replayed onto the original request (e.g. `FOS-Replay-Headers: User-Context-Hash, Page-Layout`).
4. The proxy server receives the preflight response, copies all headers that were listed in `FOS-Replay-Headers` onto the client’s original request for `/foo.php` and restarts that request.
5. If the response to this request should differ e.g. per user context, the application specifies so by setting a `Vary: X-User-Context-Hash` header. The appropriate user role dependent representation of `/foo.php` will then be returned to the client.

This would make the whole replay logic reusable for any other use case.
WDYT?

**Comment by ddeboer** [comment]
Hey, thanks for your input!

> I was wondering how much v2 is a thing already :-)

We have a [first 2.0 beta](https://github.com/FriendsOfSymfony/FOSHttpCache/releases) out for the FOSHttpCache library. The bundle is now largely updated for 2.0, so we’re getting close to a final release.

> I did not know about this bundle, nor the library up until today and actually only found it by chance 

Please let us know how we can help people like you better find this library. :wink:

> Is there any reason why you limited this? I mean, couldn't we have it way more generic?

Your use case of differentiating between two page layouts based on cookies can be implemented using the current user context functionality: just add a custom [context provider](http://foshttpcache.readthedocs.io/en/stable/user-context.html#context-providers) that looks up the user’s layout preference, which then is added to the user context hash header. By Vary’ing on that, you’ll serve different layouts based on user preference.

That said, I like your idea. I agree there’s no reason to limit the user-specific context (or ‘preflight/replay request’) to a *single* header (`X-User-Context-Hash`). Having multiple headers (e.g. one for user access level and another for the page layout preference) allows for more fine-grained Vary’ing.

> The application then returns a response containing these headers plus the general header FOS-Replay-Headers that contains a list of all headers that should be replayed onto the original request (e.g. FOS-Replay-Headers: User-Context-Hash, Page-Layout).

Are you using Varnish? Preferably, the HTTP proxy can unpack the FOS-Replay-Headers header and iterate over it without using inline C snippets or VMODs.

**Comment by dbu** [comment]
interesting idea. it does add additional complexity to the point that i wonder if we should provide a generic solution or if it makes more sense that people just use our code as a pattern and do their own thing. making this fully generic is quite complex both on the listener (register handlers that add headers) and on the caching proxy (copy the right headers).

i think we could do this in a BC way (adding FOS-Replay-Headers does not break anything, and we can provide a new separate vcl for generically handling the headers from symfony). for 2.0 its too late, but it could go into 2.1 if you want to work on it and come up with a solution that is not too complicated. i fear setting headers with variable names does need inline C in varnish however, so we might want to permanently offer both ways.

alternatively, you could write a cookbook entry for the documentation (or a blogpost that we can link to from the documentation) for this special case.

**Comment by Toflar** [comment]
> Please let us know how we can help people like you better find this library. 😉

Maybe it would have helped if I searched better :D But I still found it before started building my own solution so it can't be too bad ;)

> Your use case of differentiating between two page layouts based on cookies can be implemented using the current user context functionality

No, not quite. I know what you mean but it eventually creates the same problem as varying on `Cookie` because the hash contains too much information. E.g. when the page is made up of several ESI requests, only a few of them are different for the page layout and only a few others of them are different per user context :-) That's why I would like to add multiple headers where I can independently vary on if I like :-)

> Are you using Varnish? Preferably, the HTTP proxy can unpack the FOS-Replay-Headers header and look up the values in the preflight response without using inline C snippets or VMODs.

No I'm not for this project. The SF HttpCache is enough (might still change in the future maybe). 

> it does add additional complexity to the point that i wonder if we should provide a generic solution or if it makes more sense that people just use our code as a pattern and do their own thing. making this fully generic is quite complex both on the listener (register handlers that add headers) and on the caching proxy (copy the right headers).

Yeah, to be honest, I don't think it adds a lot of complexity. It's only splitting up responsibilities. 
So instead of a `UserContextListener` listening to its very specifiy `application/vnd.fos.user-context-hash` content type you would have something like this:

* `ReplayHeadersListener` (listens on `application/vnd.fos.replay_header`) and then dispatches its own event (e.g. `fos.replay_header`) and passing an empty `ResponseHeaderBag`.
    * `UserContextListener` includes the same logic as now, adding the `X-User-Context-Hash` (btw, [X headers are deprecated](https://tools.ietf.org/html/rfc6648)) header.
    * Other listeners, such as my `Page Layout` listener.

The code in the `ReplayHeadersListener` would look like this (outlined):

```php
public function onKernelRequest(GetResponseEvent $event)
{
    $headerBag = new ResponseHeaderBag();
    $replayEvent = new ReplayHeadersEvent($headerBag);
    $this->dispatch(ReplayHeadersEvent::EVENT_NAME, $replayEvent);

    $response = new Response('', 200, ['Content-Type' => 'application/vnd.fos.replay_header']);         
    $replayHeaders = [];
    foreach ($replayEvent->getHeaders()->all() as $k => $v) {
        $response->headers->set($k, $v);
        $replayHeaders[] = $k;
    }

    if (0 === count($replayHeaders)) {
        return;
    }

    $response->headers->set('FOS-Replay-Headers', implode(',', array_unique($replayHeaders)));
    $event->setResponse($response);
}
```

The proxy would then need to do this:

```
$headers = explode(',', $preflightResponse->headers->get('FOS-Replay-Headers''));
foreach ($headers as $header) {
    $originalRequest->headers->set($header, $preflightResponse->headers->get($header));
}
```

I'm not that much into VCL but I read that loops are not supported so maybe there's another solution for that problem. But that's exactly why I think it should be generalized. It would require us to invent one solution once and everybody can use it. 

> or if it makes more sense that people just use our code as a pattern and do their own thing

I think THIS would make it a lot more complex :-) It would require me to combine the proxy configuration in the docs of the FOSHttpCacheBundle with my own. And then suddenly one day I need yet another bundle that requires yet another configuration I need to include in my Varnish config. I just think it would be a lot better if an existing bundle that's well known in the SF community provided a generic solution for replaying headers so we can leave the door open to anyone :-) In my opinion it's separation of concerns and I'd prefer working together with you on a solution than reinventing the wheel and fighting with VCL on my own.

So imho supporting it in the SF HttpCache should be very simple. So I figure your main concern is that it would require inline C for Varnish? If there was a solution to that, would you be interested in a generic solution?

**Comment by dbu** [comment]
indeed, in php this looks quite simple. basically we would change the hash generator into an event listener instead of hard-wiring the UserContextListener with it. that all seems quite sane to me.

in VCL it will be a lot trickier. i think one intermediate step could be to hardcode the possible header names and copy them if set on the replay-lookup. the full flexible solution can't work without some inline C i fear. we should then provide the inline C as well as documentation how to write a VCL when inline C is not allowed. (inline C is super risky and must be enabled specifically in varnish)

if the matrix gets big, chances for cache hits get small and the whole operation is not worth it. but especially the use case of ESI together with VARY headers sounds like there are legitimate and useful cases.

**Comment by Toflar** [comment]
> indeed, in php this looks quite simple. basically we would change the hash generator into an event listener instead of hard-wiring the UserContextListener with it. that all seems quite sane to me.

exactly :-)



> i think one intermediate step could be to hardcode the possible header names and copy them if set on the replay-lookup.

Sounds like a good plan to me! So it would work automatically for SF HttpCache based on the `FOS-Replay-Headers` and for Varnish you would need to hardcode them in your VCL instead. Probably the same applies for Nginx, haven't checked that though.

**Comment by Toflar** [comment]
So, shall I make a PR for this then?

**Comment by dbu** [comment]
sure, go ahead!

i guess we need to decide if we put that into 2.0 (allowing for BC
breaks) or if we rather put it into 2.1 so we can release 2.0 very soon,
but then it would need a BC layer. maybe thats actually better and would
allow us to do deprecation warnings when the old accept header is used.
we then keep using the old header but trigger a warning so that people
find that in their logs and can adjust their app. if we just break it
for version 2.0, there is no grace period.

**Comment by Toflar** [comment]
Yeah, I think that's a decision you guys have to make :-) In my opinion, the beta still allows for BC breaks and nobody should be using it for production yet. Building a BC layer already before releasing a new stable major version sounds a bit awkward to me and might cause confusion :-)
I'll try to work on this asap.

**Comment by dbu** [comment]
problem is that changing the header name is a sneaky BC break that
people will not easily find. not everybody reads upgrade / changelog
information as well as they should...

i prefer to add a BC mode with deprecation messages for that reason.

**Comment by Toflar** [comment]
I have created a WIP PR so we can discuss on it :-)

**Comment by dbu** [comment]
thanks!
