### ISSUE TITLE
TagHandler on master

### ISSUE THREAD

**Issue by plozmun** [FriendsOfSymfony/FOSHttpCacheBundle#359]
I see here in documentation [here in documentation ](https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/Resources/doc/features/tagging.rst#tagging-from-code) that TagHandler is enabled to invalidate tags but the class is removed from previous version.

**Comment by dbu** [comment]
thanks for the note. seems we forgot to  update the documentation here. master will be 2.0 and is not released yet. the changelog should help: https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/CHANGELOG.md#200-unreleased 
if you can help to update the doc, we appreciate it.

**Comment by plozmun** [comment]
Then if i want to invalidate a tag from another action how i can do it ?

**Comment by plozmun** [comment]
It seems using CacheInvalidator class works! Close this issue
