### ISSUE TITLE
Add query to matching criteria in rules

### ISSUE THREAD

**Issue by helmuthva** [FriendsOfSymfony/FOSHttpCacheBundle#365]
Hi,

would be nice to be able to match based on the query string.

Best

**Comment by dbu** [comment]
the configuration in a 'match' section is used by a
``Symfony\Component\HttpFoundation\RequestMatcher`` which seems to have
no argument for the query string. i am not sure, but don't the query
string variables end up in the "attributes" part of the request?

**Comment by dbu** [comment]
ping @helmuthva

**Comment by geoffrey-brier** [comment]
@dbu only the route parameters are available within the attributes bag. Working on a prototype ;)

**Comment by dbu** [comment]
fixed in #376
