### ISSUE TITLE
FlashMessageListener constructor is invalid

### ISSUE THREAD

**Issue by wesnick** [FriendsOfSymfony/FOSHttpCacheBundle#389]
In this commit:
https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/commit/1527e44fb6c37a66573bae3e90f133984ba5eac8 , OptionsResolver was introduced.

Before you can set AllowedTypes you must set known options, hence, this class always throws an exception when instantiating.

**Comment by dbu** [comment]
fixed in #391
