### ISSUE TITLE
Anonymous and Logged In Users have the same User Hash

### ISSUE THREAD

**Issue by spointecker** [FriendsOfSymfony/FOSHttpCacheBundle#398]
Hi, 
maybe this is a stupid question but I am getting the same user hash for logged out and logged in users. (I already debugged through the Listener, Generator etc. to get this information)
Logged in users do NOT have any ROLE. I am using the role provider, with the Symfony Cache implementation.
This results of course in wrongly used caches.
I set the TTL of the hash cache to 0.

Is this normal? Any suggestions on debugging that?

**Comment by spointecker** [comment]
`isAnonymous()` in the `UserContextListener` always returns `false`, cause Symfony always sets the Session Cookie.

**Comment by spointecker** [comment]
I solved this by setting a default user role for generic logged in users.

**Comment by dbu** [comment]
glad that you found the solution.

if you start a session, symfony considers people as logged in anonymous afaik. and thus indeed when a person actually logs in you need an actual role for that if you distinguish.

do you have a suggestion where in the documentation we could mention this to avoid other people being confused by this? (or not noticing that they have a problem)

**Comment by spointecker** [comment]
I think it would be good to have a more detailed description of how to implement the Bundle with Symfony HttpCache in general.
Like
- the problem from above
- how to setup the app.php file (Store, ESI, ...)
- SSL certificate problems on purge/refresh on dev machines

Those were the parts which took me the most time to find out due to the lack of documentation and information on the web (aka Stackoverflow).
