### ISSUE TITLE
Cache tags between app environments

### ISSUE THREAD

**Issue by ddeboer** [FriendsOfSymfony/FOSHttpCacheBundle#408]
We have an app that has different environments (staging, production) running on the same Varnish instance. When deploying, we need to invalidate some tags. When deploying to (e.g.) staging, production data with the tag in question will be invalidated, too.

How do others handle this situation? Of course, we could have a separate Varnish instance for each environment. Alternatively, would adding a ‘global tag prefix’ param make sense? In `parameters.yml` users can then set that param to (e.g.) `staging` or `production`. When tagging and invalidating, all tags will be prefixed thus, so `staging-tag1` etc.

**Comment by dbu** [comment]
i think having separate varnishes would be an excellent idea, as then you can also integration test your caching configuration, and don't load the production varnish with staging traffic... but i am sure you are aware of that.

next level could be to accept that you sometimes invalidate more than necessary. its only cache, after all...

the prefix would surely work. you could do a custom version of the TagHeaderFormatter that adds the prefix, and extend the Varnish proxy client to overwrite `escapeTags` and also add the prefix. however, the whole thing feels too much of an antipattern to me to provide in the library. we should not encourage people to do it. when you have many tag invalidations, things seriously slow down on varnish. adding several environments to that makes the problem worse.

**Comment by ddeboer** [comment]
> next level could be to accept that you sometimes invalidate more than necessary. its only cache, after all...

True, but we’re noticing some impact on the production system because a lot of cache gets invalidated at once. Usually, caches expire at different times, so the effect is less noticeable. 

> however, the whole thing feels too much of an antipattern to me to provide in the library.

Agreed, thanks!
