### ISSUE TITLE
Question: Slack channel / docs update

### ISSUE THREAD

**Issue by Toflar** [FriendsOfSymfony/FOSHttpCacheBundle#411]
Hey guys,

I recently found it's way easier to get in touch with the people involved in a project (API platform that was for me) when there's a slack channel where you can just float in a question and anybody can help or discuss some features/bugfixes in more detail easily. Not sure what's the requirements to get a channel on `symfony-devs.slack.com` but what's the general feedback on having that?

We could document that in the `Contributing` section too so that FOSHttpCache rookies can find us 😄

**Comment by dbu** [comment]
there is the friendsofsymfony channel in the symfony devs slack. i think we should point to that channel. its not too busy atm. want to do a PR to update the readme and the documentation to point to the symfony slack signup and indicate the channel?

**Comment by Toflar** [comment]
Closing in favor of https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/pull/412
