### ISSUE TITLE
400 Error response "Bad Request"

### ISSUE THREAD

**Issue by cduran433** [FriendsOfSymfony/FOSHttpCacheBundle#429]
Sorry for my bad English.

I am going to explain my situation, I just install the FOSHttpCacheBundle with the Symfony HTTP-cache proxy. Headers are working fine but right now I want to invalidate some paths.

I execute : 
`php app/console fos:httpcache:invalidate:path http://www.example.com/app_dev.php/en`

Output:
```
[FOS\HttpCache\Exception\ExceptionCollection]
  400 error response "Bad Request" from caching proxy
```

I am using the dev environment to test it here before release to production.

Symfony logs are:
`::ffff:172.18.0.11 - - [08/Feb/2018:15:25:02 +0000] "PURGE /app_dev.php/en HTTP/1.1" 400 5 "-" "GuzzleHttp/6.2.1 curl/7.35.0 PHP/5.5.9-1ubuntu4.22" `

I am using this version:
friendsofsymfony/http-cache              2.1.1      
friendsofsymfony/http-cache-bundle       2.1.2  

I think that I need to configured something else, but I don't know what I am missing. Any idea?

**Comment by dbu** [comment]
did you read the documentation chapter on adjusting your HttpCache class? http://foshttpcache.readthedocs.io/en/latest/symfony-cache-configuration.html

is the cache class using the EventDispatchingHttpCache trait and registering the event listeners that you want to use?

**Comment by dbu** [comment]
PS: no worries, your english is perfectly understandable ;-)

**Comment by dbu** [comment]
i am closing this, but feel free to reopen if you have further questions
