### ISSUE TITLE
Add support for Varnish xkey

### ISSUE THREAD

**Issue by dbu** [FriendsOfSymfony/FOSHttpCacheBundle#431]
Make the features of https://github.com/FriendsOfSymfony/FOSHttpCache/pull/332 available through configuration.

The xkey setting should be shared between ResponseTagger and Varnish client to change all headers to the correct default.

**Comment by andrerom** [comment]
Could you expand on how it should be done, in detail? _(point to existing settings this can be modeled after, expand on what the setting should be named and how it should behave)_

**Comment by dbu** [comment]
i didn't look into it in detail yet. looking at the Configuration class, i see there is the `addTagSection` method for the `tags` part of the configuration. i think this is where the config should go. something like `tag.mode` to be consistent with the naming in FOSHttpCache.
we can then add a new validate function at the top of Configuration to check that if the tags method is xkey, the client indeed is varnish, and change the appropriate defaults of the varnish configuration to take into account whether the xkey or ban method is used for tags, and set up the response tagger accordingly.
i added some of that default behaviour in FOSHttpCache already - maybe we can simply change some defaults to be null instead of repeat the default value from the library to get FOSHttpCache to pick things up. (like the tag header option for the Varnish client)

does that help?

**Comment by andrerom** [comment]
This will also have to be dealt with:
`$this->addTags(explode(',', $response->headers->get($this->getTagsHeaderName())));`

**Comment by dbu** [comment]
oh, indeed. that one is for merging the tags, right?

**Comment by andrerom** [comment]
https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/src/Http/SymfonyResponseTagger.php#L29-L42

**Comment by dbu** [comment]
I tagged 2.2.0 of the bundle without this, because the Symfony 4 support has been waiting for a release for too long already. I have no problems tagging a 2.3.0 in a week or whenever we have the xkey support ready.

**Comment by andrerom** [comment]
Good to know @dbu. This is up for grabs if anyone what to add the config for this btw, instructions above should give enough clues to it.

**Comment by dbu** [comment]
fixed in #464
