### ISSUE TITLE
Autowiring deprecation notice

### ISSUE THREAD

**Issue by XWB** [FriendsOfSymfony/FOSHttpCacheBundle#453]
After autowiring my commands and automatically injecting the CacheManager, I got the following deprecation notice:

> Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "fos_http_cache.cache_manager" service to "FOS\HttpCacheBundle\CacheManager" instead.

**Comment by dbu** [comment]
i am confused. i thought we added the autowiring aliases, but it seems that never happened here. i will add them asap...

**Comment by dbu** [comment]
@XWB can you please check #454 and tell me if it fixes your issue?

**Comment by XWB** [comment]
@dbu Tested & it works like a charm :+1:
