### ISSUE TITLE
UserContext Caching with Symfony

### ISSUE THREAD

**Issue by danrot** [FriendsOfSymfony/FOSHttpCacheBundle#459]
The UserContext feature is documented to be[ working with Symfony Cache](http://foshttpcachebundle.readthedocs.io/en/latest/features/user-context.html) in the documentation.

However, this doesn't work anymore, because the [UserContextInvalidator](https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/src/UserContextInvalidator.php#L39) requires the `BanCapable` interface, and this requirement is not matched for the Symfony ProxyClient. Therefore the application already fails when building the container.

I don't know what exactly is happening here, but either we get rid of the hard dependency on the `BanCapable` interface or the documentation should be changed in order to reflect that this feature is not working with Symfony Cache.

**Comment by dbu** [comment]
we should not activate the user context invalidator with symfony proxy client, because the symfony proxy does not support banning. is that invalidator automatically activated? or did you configure something to activate it? according to the [doc](http://foshttpcachebundle.readthedocs.io/en/latest/reference/configuration/user-context.html#logout-handler) i think it should be on `auto` - which should decide `false` when using the symfony proxy. we could edit the text about ban capable to be more explicit.

**Comment by danrot** [comment]
Looks to me like it is activated as soon as the user context feature is activated, since it is in the [`user_context.xml` configuration file](https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/src/Resources/config/user_context.xml#L28). However, it only seems to happen if a proxy client is configured. So adding a proxy client seems to activate that invalidator...

**Comment by dbu** [comment]
yeah, you are right: https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/849954c7ac4e6a55a4bdaeb9ab20ad2a5ebc5fd2/src/DependencyInjection/Configuration.php#L91-L120 only takes into account whether there is a cache manager, not which one.

and then the `auto` is already resolved when we go to the extension
https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/1c96c02728399c1dfc1c0806d98c60e10deace10/src/DependencyInjection/FOSHttpCacheExtension.php#L313-L323

i think we should change that validate function to always trigger if the invalidation is not disabled, and then check if both cache manager and proxy client are active. and if its set to `auto` also check if the client is set to something that we know is not ban capable, and disable in that case as well.

do you want to do a pull request for this?

**Comment by danrot** [comment]
TBH that was just for a university course, which is already finished now, so it's not that important for me anymore, and I've got not too much time currently... Maybe I will do a PR at some point, but I can't do it in the near future. But still wanted to let you know :-)

**Comment by dbu** [comment]
fair enough, thanks for reporting the issue. its now at least documented.
