### ISSUE TITLE
Symfony 3.4.12 issue with 1.x?

### ISSUE THREAD

**Issue by andrerom** [FriendsOfSymfony/FOSHttpCacheBundle#465]
After update today to 3.4.12 we are seeing the following:
![screen shot 2018-06-25 at 14 46 34](https://user-images.githubusercontent.com/289757/41869946-de22c2c4-78ba-11e8-927a-ad27a32701ce.png)

Not looked deeply at it yet, so for now just asking if someone has seen the same.

**Comment by andrerom** [comment]
Ok, seems it's caused by new method added in Abstract in symfony: https://github.com/symfony/symfony/compare/v3.4.11...v3.4.12#diff-5350dc763df30ada9d00563c115f6652R68

@dbu Seems the following code is a bit risky, either extend or not reuse event subscribers from another class?
https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/src/EventListener/SessionListener.php#L84-L87

**Comment by spointecker** [comment]
Same here

**Comment by emodric** [comment]
@andrerom I don't know if there's any better way to disable setting the cache to private for user context based pages, but I would say no, at least not in Symfony 3.4. @Toflar was the original author of the patch (#435), he could have some more insights.

The original issue: #433

**Comment by Toflar** [comment]
Well there's not much more insight to give. Decorating the listener is the only way to disable the core behaviour for versions lower than 4.1. I knew it's going to cause issues so I created a PR for Symfony 41 (https://github.com/symfony/symfony/pull/26681) to make sure we can easily disable the behaviour without decorating the listener in newer versions. But yeah, for versions lower than 4.1 we just have to keep up with the changes of Symfony itself 😢

**Comment by Toflar** [comment]
In Contao we're using a similar approach (not using the UserContext there) and it's already fixed. See https://github.com/contao/core-bundle/commit/db8ed610d9642e7d1fa8cd03462128ac295ebc11. So in case anybody wants to help @dbu with a PR, that would be awesome 😄

**Comment by phibo23** [comment]
we also encountered this issue while updating to ezplatform. our workaround is to stay on FOSHttpCacheBundle 1.3.13. The issue seems to be introduced with 1.3.14.

**Comment by dbu** [comment]
fixed in https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/releases/tag/1.3.16 - i will now update master and release 2.4.1

**Comment by dbu** [comment]
i could use some help in #473 - tests fail on master and i don't really understand why.
