### ISSUE TITLE
You have requested a non-existent service "FOS\HttpCacheBundle\CacheManager".

### ISSUE THREAD

**Issue by Zyostes** [FriendsOfSymfony/FOSHttpCacheBundle#467]
I have this issue in latest release v2.4.0 and Symfony v4.0.7 (reported here https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/issues/458 for another version).
I tried to break something in cache_manager.xml but nothing happens, I think it is not loaded.

I used this in my controller :
`$cacheManager = $this->get(CacheManager::class);`

When I launch debug:autowiring, I have only this line for HttpCacheBundle : 

```
FOS\HttpCacheBundle\EventListener\CacheControlListener                              
      alias to fos_http_cache.event_listener.cache_control       
```

Thank you for your very good work !

**Comment by dbu** [comment]
does the same configuration work with a 2.3 version of this bundle? it sounds indeed like the cache manager is not loaded at all. but it should be loaded, there was no intended behaviour change.

i am currently on holidays - if you have some time to debug and try to figure out what the difference is, i appreciate. i can look at it in one week, hopefully.

**Comment by bassrock** [comment]
Looks like the issue is that you need to enabled the cache manager and a proxy client first.

**Comment by dbu** [comment]
@bassrock did it change for you when upgrading, or did you start using the bundle? if the former, can you see the difference why we would no longer load the manager with the same config as before?

**Comment by bassrock** [comment]
I just started using the bundle. I didn't realize you needed a proxy client setup and to enabled tags or the options you needed for it to work. I think it was more of a didn't read the documentation properly issue.

**Comment by dbu** [comment]
ok, cool. i think there is no way we can avoid this, apart from if we had a symfony flex recipe.
