### ISSUE TITLE
Using the AbstractSessionListener to fetch events breaks fos cache since symfony 3.4.12

### ISSUE THREAD

**Issue by samvdb** [FriendsOfSymfony/FOSHttpCacheBundle#469]
The method onFinishRequest is not available in the session listener.

Since patch 3.4.12 this method is added and also returned in the getSubscribedEvents array.
This version contains the old array.
https://github.com/symfony/http-kernel/blob/v3.4.11/EventListener/AbstractSessionListener.php

Now the following exception is thrown: 
Warning: call_user_func() expects parameter 1 to be a valid callback, class 'FOS\HttpCacheBundle\EventListener\SessionListener' does not have a method 'onFinishRequest'

Line containing the error:
https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/6b75eba45d8c87082c2f66a6e9882b5a1359f72b/src/EventListener/SessionListener.php#L86

**Suggested fix:**

Implement getSubscribedEvents in the listener, not sure if this breaks anythings with the priorities.

**Comment by dbu** [comment]
see #466

thanks for looking into this @samvdb . i think your approach with lowering the priority made the listener not being executed.
