### ISSUE TITLE
Remove tags header in case of SF proxy

### ISSUE THREAD

**Issue by Toflar** [FriendsOfSymfony/FOSHttpCacheBundle#475]
Right now in the case of the Symfony proxy, the `x-cache-tag` header is exposed to the world. We would need to have some option to remove the header during `kernel.response` but still make sure the tags are there during `kernel.terminate` so they can be invalidated.

Any ideas?

**Comment by dbu** [comment]
agreed that this is not ideal. maybe the tag invalidation plugin could register for the response event as well, and store the tags into itself and remove the header, then use its local data in kernel.response instead of the header? i am not 100% sure if all will go well with sub requests and if there are other edge cases

**Comment by Toflar** [comment]
I don't think it's necessarily wrong that the response is tagged. In the case of the Symfony proxy the invalidation listener should just also register on `kernel.response` with a very low priority and remove does headers and store them internally so it can pass them on during `kernel.terminate`. However, to do so, it needs to know if the current cache supports that and that would mean we need some new capability interface in the `CacheManager` so only the Symfony proxy could implement that. What do you think about that idea?

**Comment by dbu** [comment]
i don't have the flow super present. do we really mark tags on the response in the tags header when we want to invalidate tags? https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/6726a2374ad100c9f824ece4f2734bb01e7dc521/src/EventListener/TagListener.php#L117 only records that we need to invalidate tags. we later *send* a request to all caches with the tags to invalidate, but that is something else.

if we never use the x-cache-tags header to know what to invalidate, we should have the cachekernel plugin remove the x-cache-tags after storing the response in the cache.

**Comment by Toflar** [comment]
I've looked into it and I think what we need to do is to use the `POST_HANDLE` event. Just [like the `CustomTtlListener` that cleans up the response](https://github.com/FriendsOfSymfony/FOSHttpCache/blob/master/src/SymfonyCache/CustomTtlListener.php#L103), there should be one I can register myself to clean up the cache tags.

Like so:

```php
namespace FOS\HttpCache\SymfonyCache;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;

class CleanupCacheTagsListener implements EventSubscriberInterface
{
    /**
     * @var string
     */
    private $tagsHeader;

    /**
     * @param string $tagsHeader The header that is used for cache tags.
     */
    public function __construct($tagsHeader = 'X-Cache-Tags')
    {
        $this->tagsHeader = $tagsHeader;
    }

    /**
     * Remove the cache headers.
     *
     * @param CacheEvent $e
     */
    public function cleanResponse(CacheEvent $e)
    {
        $e->getResponse()->headers->remove($this->tagsHeader);
    }

    /**
     * {@inheritdoc}
     */
    public static function getSubscribedEvents()
    {
        return [
            Events::POST_HANDLE => 'cleanResponse',
        ];
    }
}
```

And then in the kernel one has to do this:

```php
use FOS\HttpCache\SymfonyCache\CleanupCacheTagsListener;

class SuperKernel extends HttpCache
{
    use EventDispatchingHttpCache;

    /**
     * @param KernelInterface $kernel
     * @param string|null     $cacheDir
     */
    public function __construct(KernelInterface $kernel, string $cacheDir = null)
    {
        parent::__construct($kernel, $cacheDir);

        $this->addSubscriber(new CleanupCacheTagsListener()); // Specify custom header if you want.
    }
}
```

**Comment by Toflar** [comment]
It's library anyway, so let's move the discussion to the PR I've just created: https://github.com/FriendsOfSymfony/FOSHttpCache/pull/422
