### ISSUE TITLE
Symfony Proxy Client - Tag Invalidation

### ISSUE THREAD

**Issue by trickreich** [FriendsOfSymfony/FOSHttpCacheBundle#478]
When I'm asking the `CacheInvalidator` via `supports` method if the Symfony supports the tag invalidation it returns true because the `TagCapable` interface is implemented for that client.
In fact a tag invalidation is only support for Symfony if you install one more dependency.
So what we can do here? Check in our application if this bundle is installed and don`t use the `supports` method?

**Comment by dbu** [comment]
ugh. thats indeed not ideal. can you send a pull request against the FOSHttpCache library that puts that logic into the CacheInvalidator? make supports check is for tag capable and the proxy client is symfony, check if the tags thing is set up?

are you building a reusable component that needs to know the supports? if you build an application, i would not use support as you will know what is installed in your application...

**Comment by dbu** [comment]
right, in such a context its valid to want to use supports. looking forward to the pull request then.

**Comment by trickreich** [comment]
One question left: From which version I should start?

**Comment by dbu** [comment]
i prefer not to maintain too many minor versions unless there is a severe security problem. if you could do it against the master branch, i can then tag 2.4.1 with the fix.

**Comment by trickreich** [comment]
Alright :+1:

**Comment by dbu** [comment]
fixed in #425
