### ISSUE TITLE
Do we have a callback kind of hook when a request match is found for tags and invalidation section

### ISSUE THREAD

**Issue by ranjzith** [FriendsOfSymfony/FOSHttpCacheBundle#480]
Hi Team,

I am new to to FOSHttpCacheBundle and going through the docs for the integration with Varnish, I came across this requirement where I had to invalidate few URLs on a match, which I had to fetch from a REST API. Could you please let me know, whether or not we have such a hook in the YML configurations, where we can register a service (extending one of the interfaces) and a specific method would be called when the match is found.

Any lead on this would be grateful.

Thanks!

**Comment by dbu** [comment]
unless i miss something, you can only specify a static list. however, you could write your own request listener using the matchers we provide in this bundle, and inject the proxy client to have your listener send the invalidation requests as needed.

**Comment by dbu** [comment]
if its only on requests that end up at one specific controller, you could also have the controller trigger the invalidation. depends on your design what makes more sense...

**Comment by ranjzith** [comment]
Thank you @dbu, I will try with the request listener approach.
