### ISSUE TITLE
Subroutines VCL are missing

### ISSUE THREAD

**Issue by tristanbes** [FriendsOfSymfony/FOSHttpCacheBundle#488]
Hello,

Documentation states [here](https://foshttpcache.readthedocs.io/en/latest/varnish-configuration.html#provided-vcl-subroutines): 
> Subroutines are provided in resources/config/varnish-[version]/fos_purge.vcl.

The problem is that there is no such configuration files in the [repository](https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/tree/master/src/Resources/config
)

So, where did the subroutines go ? :D

**Comment by dbu** [comment]
you opened this issue on the bundle that integrates the FOSHttpCache library into symfony. the VCL files are part of the library and exist in the FOSHttpCache repository: https://github.com/FriendsOfSymfony/FOSHttpCache/tree/master/resources/config . 

i added a link in the doc https://github.com/FriendsOfSymfony/FOSHttpCache/pull/431 to avoid confusion. the bundle documentation points to the library in a couple of places (to avoid redundancy) but that makes it not very obvious if one is reading bundle or general library doc.

**Comment by tristanbes** [comment]
Thanks, sorry for the confusion :-)

**Comment by dbu** [comment]
np, glad it was easy to solve ;-)
