### ISSUE TITLE
Hard dependency on sensio/framework-extra-bundle when using cache tagging

### ISSUE THREAD

**Issue by Toflar** [FriendsOfSymfony/FOSHttpCacheBundle#489]
I'm not quite sure if I got this right, so I figured I'll add an issue first and get your opinion but the parameter `fos_http_cache.compiler_pass.tag_annotations` in https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/src/DependencyInjection/Compiler/TagListenerPass.php#L28 is set to `true` as soon as you enable cache tagging (https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/src/DependencyInjection/FOSHttpCacheExtension.php#L108-L119).

Why is this?

I mean, what's wrong in having all the cache tagging logic/services (`cache_tagging.xml`) without support for annotations? I only add my tags using code.

**Comment by Toflar** [comment]
Yeah I see, however, I don't really know how to deal with the existing `auto` configuration. That whole setting makes no sense to me 😄 Also, why is it done so complicated in a compiler pass and not just a `class_exists()` on the bundle class itself? I mean, we don't really care how the bundle adds support for annotations, just the fact that it's there should be enough, no?

**Comment by dbu** [comment]
class_exists does not tell you if the service really is loaded. the tought about `auto` was more of a tangent. the existing "auto" for tagging is to enable it if we know the cache supports it.

i'll try to do something this evening.

**Comment by Toflar** [comment]
Cool, thank you!
