### ISSUE TITLE
Confused about the kernel dispatcher documentation

### ISSUE THREAD

**Issue by alexander-schranz** [FriendsOfSymfony/FOSHttpCacheBundle#490]
I'm not correctly understanding what the `index.php` should look like for the [**kerneldispatcher**](https://foshttpcachebundle.readthedocs.io/en/latest/features/symfony-http-cache.html#optimization-for-single-server-installations)  setup:

If I look at the linked documentation: https://foshttpcache.readthedocs.io/en/latest/proxy-clients.html#kerneldispatcher-for-single-server-installations

The following lines:

```php
// Tell the kernel about the cache
$kernel->setHttpCache($httpCache);

// Create the Symfony proxy client with KernelDispatcher
$kernelDispatcher = new KernelDispatcher($kernel);
$symfony = new Symfony($kernelDispatcher);
```

are confusing me.

Should it not be enough the following implementation:

```diff
// ...
$kernel = new Kernel(...);

+ if (SYMFONY_ENV !== 'dev') {
+     $kernel = new HttpCache($kernel);
+ }
```

If I look at the symony basic [index.php](https://github.com/symfony/demo/blob/master/public/index.php) there is no KernelDispatcher or Symfony. Also not clear if $httpCache->handle need to be called or `$kernel->handle` I'm really confused if this lines are really needed.

**Comment by dbu** [comment]
hi, that documentation is about the stand alone library and therefore instantiates the kernel dispatcher and symfony proxy client. however, i see how this is confusing because we have the bundle doc pointing to that section... i will attempt to clarify it in a PR

**Comment by dbu** [comment]
can you please review #490 and tell me if that is more understandable?

note that the whole thing is about using in-process communication between the symfony AppCache and the actual application. its a small optimization and it would work perfectly fine to have the application talk to the kernel with a HTTP request.

**Comment by alexander-schranz** [comment]
@dbu thank you that make it more clear. And is ok for to merge it as it is. 
But I'm interesting in your opinion moving the creation of the HttpCache class into the kernel constructor to avoid changing the console. Example: https://github.com/sulu/sulu-minimal/pull/122/files#diff-200e568e631da779466e1e2520aabc7e

**Comment by dbu** [comment]
excellent idea, thanks! the documentation has become much easier that way. and as the kernel needs to know about the cache kernel anyways, i don't see any harm in doing things that way.

**Comment by alexander-schranz** [comment]
@dbu awesome, thank you!
