### ISSUE TITLE
Help needed for UserContext usage with a cookie value

### ISSUE THREAD

**Issue by Gog0** [FriendsOfSymfony/FOSHttpCacheBundle#500]
Hello,

I'm trying to use your bundle for the first time and there is something that I'm missing.

I'm trying to use the UserContext feature and I made my own:
```
class UserPreferenceContextProvider implements ContextProvider
{
    private $requestStack;

    public function __construct(RequestStack $requestStack)
    {
        $this->requestStack = $requestStack;
    }

    public function updateUserContext(UserContext $userContext)
    {
        $request = $this->requestStack->getMasterRequest();
        $currency = $request->cookies->get('currency');
        $userContext->addParameter('currency', $currency);
    }
}
```

The idea is to cache different variations of cached pages based on the currency chosen by the user which is store in a cookie called 'currency'. But for whatever reason I always get the the same response for any cookie value sent. The cookie value is an integer between 1 and 4.

Do you have any idea what I could be doing wrong?

**Comment by XWB** [comment]
Indeed, make sure Varnish does not remove that particular cookie.

```
sub vcl_recv {
    set req.http.cookie = ";" + req.http.cookie;
    set req.http.cookie = regsuball(req.http.cookie, "; +", ";");
    set req.http.cookie = regsuball(req.http.cookie, ";(PHPSESSID|currency)=", "; \1=");
    set req.http.cookie = regsuball(req.http.cookie, ";[^ ][^;]*", "");
    set req.http.cookie = regsuball(req.http.cookie, "^[; ]+|[; ]+$", "");
}
```

**Comment by dbu** [comment]
feel free to reopen for further discussion if you checked these things and do them correctly.
