### ISSUE TITLE
Accessing request headers for user_context_hash request

### ISSUE THREAD

**Issue by ranjzith** [FriendsOfSymfony/FOSHttpCacheBundle#503]
Hi,

I am using Varnish 4 with Apache Httpd with Symfony3 as the backend.

I am looking for a way to access request headers sent along with /_fos_user_context_hash request in my context provider class. I had to generate the hash based on the original request URI for one of my use case. Could you suggest me an approach on this.

Thanks.

**Comment by ranjzith** [comment]
Found a way by injecting the request stack service into the  context providers constructor. Please correct me if there is another approach.

Thanks.

**Comment by dbu** [comment]
injecting the request stack is the correct way to go here :+1: 

the user context code itself is not symfony dependent, so it can't pass the symfony request object to the context provider.
