### ISSUE TITLE
Exposed Symfony-Session-NoAutoCacheControl header when sessions are disabled

### ISSUE THREAD

**Issue by Tobion** [FriendsOfSymfony/FOSHttpCacheBundle#512]
The `UserContextListener` sets the `Symfony-Session-NoAutoCacheControl` header. But if a project does not even use sessions and disabled it, then the `\Symfony\Component\HttpKernel\EventListener\SessionListener` is not active. And thus also does not remove this header again. So FOSHttpCacheBundle should not set this header when sessions are not enabled in https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/eacce6e423619fd2133862e185afeabf681a4aab/src/EventListener/UserContextListener.php#L151 and https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/eacce6e423619fd2133862e185afeabf681a4aab/src/EventListener/UserContextListener.php#L215

Otherwise it exposes this header to the outside.

**Comment by dbu** [comment]
oh, indeed. how would you go about detecting whether the applications has sessions enabled? an explicit configuration would work, but is not exactly user-friendly as you would need to be aware of the topic.  is there some clean way to determine if sessions are active or not? or should this bundle do a compiler pass that looks for the session listener?

i noticed that the only documentation about the header is on the [session listener class](https://github.com/symfony/symfony/blob/7f3f75d85d6a63b8561d7ce44244b82e9fe63b9c/src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php#L27-L31) - i guess we should also create a small documentation entry that explains this a bit and recommends how to detect if sessions are active.

**Comment by dbu** [comment]
after discussion with tobi: we should do the compilar pass approach to check whether session_listener is defined and disable the magic header if the session_listener is not defined.
