### ISSUE TITLE
fos_http_cache.cache_manager service could not be found

### ISSUE THREAD

**Issue by roland4432** [FriendsOfSymfony/FOSHttpCacheBundle#513]
Trying to get the fos_http_cache.cache_manager service, symfony crashes with "You have requested a non-existent service "fos_http_cache.cache_manager" while using symfony 2.8.49

The config:

cache_manager:
        enabled: true
        custom_proxy_client: ~
        generate_url_type: true

=> ~ not working for custom_proxy_client
=> generate_url_type: true is not a valid input

Most of the docs are not even close to allowed configurations when checking the DI Configuration.php
Dozens for errors, misconfiged parameters and a bunch of not working classes or missmatches between doc and code.

**Comment by dbu** [comment]
hi,

i provide this bundle as is, for free because its interesting to do and we use it in client projects. please keep that in mind. you are welcome to help improving the documentation if you find something confusing or if something is out of sync.

looking at https://foshttpcachebundle.readthedocs.io/en/latest/reference/configuration/cache-manager.html#generate-url-type and at https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/eacce6e423619fd2133862e185afeabf681a4aab/src/DependencyInjection/Configuration.php#L624-L633, the values come from UrlGeneratorInterface. afaik `true` is one of the values, for historical reasons.

the current version of the bundle supports symfony 3.4.4 and newer. did you look at the correct version of the documentation for what you use?

if the enum does not work with a boolean, could you please provide a pull request that adds a test to https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/tests/Unit/DependencyInjection/ConfigurationTest.php to demonstrate the problem? if i can see the problem, i can try to find a fix for it.

**Comment by roland4432** [comment]
Nontheless this is just a side issue.
The bigger problem is the fact, that the mentioned service ist not available.
To clear things up, this is what I wanted to achieve a cache invalidator, that will clear a cache for a pages when the corresponding url is called in app_dev mode:

`class HttpCacheInvalidatorListener {

    protected $isDevEnvironment;
    private $container;

    public function __construct(ContainerInterface $container, $kernelEnvironment){
        $this->isDevEnvironment = $kernelEnvironment == 'dev';
        $this->container = $container;
    }

    public function onKernelRequest(GetResponseEvent $event){
        if($event->isMasterRequest() && $this->isDevEnvironment){
            try {
                $cm = $this->container->get('fos_http_cache.cache_manager');
                $cm->invalidatePath($event->getRequest()->getPathInfo())->flush();
            } catch (ExceptionCollection $e) {
                  echo $e->getMessage();
            }
        }
    }
}`

With the yml config:

`services:
    kernel.listener.cache_invalidator:
        class: S5App\CoreBundle\Services\HttpCacheInvalidatorListener
        arguments:
          - "@service_container"
          - "%kernel.environment%"
        tags:
          - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest}
`

Wherever I use or reference "fos_http_cache.cache_manager" I get an error that this service is not defined.
A look in the docs @ https://foshttpcachebundle.readthedocs.io/en/2.4.1/reference/configuration/cache-manager.html?highlight=cache_manager
tries to configure the cache_manager.

So your Extension in the Dependency Injection folder checkes for: 
`if ($config['cache_manager']['enabled']) {`

and to enable it I need to add this to my config:

`cache_manager:
        enabled: true
        custom_proxy_client: ~
        generate_url_type: true
`
which is not working due to the things I mentioned above.
Btw: Since true === 1 is false the check from the Configuration.php fails ofc when checking true against UrlGeneratorInterface::ABSOLUTE_URL

So source of my problem is, that I cannot get the service "fos_http_cache.cache_manager".

**Comment by dbu** [comment]
okay, that documentation page is indeed confusing, and the generate_url_type has been changed to the constants of [UrlGeneratorInterface](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Routing/Generator/UrlGeneratorInterface.php#L34-L55) which has 0, 1, 2, 3 as values. 

i will fix that documentation, thanks for bringing it to my attention.

can you show your full fos_http_cache configuration please? the cache manager should automatically be available if you configure a proxy client. the documentation on the cache manager is for when you configure your own proxy client service. the cache manager needs to know how to talk to your http cache (and if that is a symfony httpcache or varnish or nginx...)

**Comment by roland4432** [comment]
Hello,

this is the import part of my config:

    parameters:
      default_cache_headers:
        cache_control: { public: true, max_age: 1800, s_maxage: 3600 }
        etag: strong
      no_cache:
        cache_control: { no_cache: true, public: false, max_age: 0, s_maxage: 0 }

    services:
      kernel.listener.cache_invalidator:
        class: S5App\CoreBundle\Services\HttpCacheInvalidatorListener
        arguments:
          - "@service_container"
          - "%kernel.environment%"
        tags:
          - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest}

    fos_http_cache:
      cache_manager: (this part is not working)
        enabled: true
        custom_proxy_client: "@fos_http_cache.proxy_client.symfony"
        generate_url_type: auto
      cache_control:
        defaults:
            overwrite: true
        rules:
            - match:
                  attributes: { _controller: Admin }
              headers: '%no_cache%'

            - match:
                  query_string: (^|&)nocache=
              headers: '%no_cache%'

            - match:
                  path: ^/xyz*
              headers: '%default_cache_header%

After some digging in the symfony HTTPCache Core stuff, I found a solution for the included CacheInvalidator for Symfony internal HTTPCache:

    class HttpCacheInvalidatorListener {

      protected $isDevEnvironment;
      private $container;

      public function __construct(ContainerInterface $container, $kernelEnvironment){
          $this->isDevEnvironment = $kernelEnvironment == 'dev';
          $this->container = $container;
      }

      public function onKernelRequest(GetResponseEvent $event){
          if($event->isMasterRequest() && $this->isDevEnvironment){
              $store = new Store($this->container->getParameter('kernel.cache_dir') . '/../prod/http_cache');
              $request = Request::create(str_replace('app_dev.php/', '', $event->getRequest()->getUri()));
              $store->purge($request->getUri());
          }
      }
    }

I hope this helps. If you need more specific details, I can help with that as well.

**Comment by dbu** [comment]
alright, if that is all configuration you have, then the problem is that you did not configure the proxy client. you need to tell FOSHttpCache what reverse proxy you use for caching and how to talk to that. see https://foshttpcachebundle.readthedocs.io/en/latest/reference/configuration/proxy-client.html#symfony . if you are running symfony on one single server, look at the `use_kernel_dispatcher` note.

please also note that you need to build your http cache to support invalidation: https://foshttpcache.readthedocs.io/en/latest/symfony-cache-configuration.html

**Comment by roland4432** [comment]
If I config:

    use_kernel_dispatcher: true

then this error is thrown:

    Type error: Argument 1 passed to FOS\HttpCache\SymfonyCache\KernelDispatcher::__construct() must be an instance of FOS\HttpCache\SymfonyCache\HttpCacheProvider, instance of AppKernel given, called in /var/www/webproject/app/cache/dev/appDevDebugProjectContainer.php on line 5448

The other stuff in the config seems working. Thank you for pointing this out :+1:

**Comment by dbu** [comment]
please read the documentation that i linked to:

> use_kernel_dispatcher: true instead. This will call the kernel directly instead of executing a real HTTP request. Note that your kernel and bootstrapping need to be adjusted to support this feature. The setup is explained in the Symfony HttpCache chapter.

that links to https://foshttpcachebundle.readthedocs.io/en/latest/features/symfony-http-cache.html#symfony-http-cache-kernel-dispatcher which explains how to set up the kernel.
