### ISSUE TITLE
Synchronous client in test env

### ISSUE THREAD

**Issue by dkarlovi** [FriendsOfSymfony/FOSHttpCacheBundle#527]
If you're pushing invalidation requests in functional tests to Varnish, the currently registered `FOS\HttpCache\ProxyClient\HttpDispatcher` will do all the request

> Queue and send HTTP requests with a Httplug asynchronous client.

This makes it harder to assert something just as you've sent the invalidation request since you'll run into race conditions. It would be great if the bundle would swap out to a synchronous in `test` env by default.

**Comment by dbu** [comment]
i see your point. if you have an idea how to do that (e.g. a flag in our client thing to have it wait for the response that one can use in the test env, and possibly also if there are other race condition issues in a scenario), feel free to do a pull request for this. it could maybe also be solved in the config of httplug but if we have a clever solution in the bundle that might be more user friendly.

**Comment by dkarlovi** [comment]
I can't think of scenarios where you'd want an async client in your tests TBH.

The best approach seems be to have a config option which swaps out the entire client implementation for one without async and enable it by default in `test` mode?

**Comment by dbu** [comment]
the http dispatcher typehints an async client. however, it already waits for the promises to resolve: https://github.com/FriendsOfSymfony/FOSHttpCache/blob/56dd01d382f390a866aed955f10f09f28b58dd6e/src/ProxyClient/HttpDispatcher.php#L152

what exactly is the issue you have? is it that dispatching only happens on kernel terminate? in symfony functional tests, terminate either already happened or reliably won't happen until the test is done (not sure which) - there is no concurrency in php. if you have an integration test that sends actual http requests to your application, you could look into building a custom listener to flush the proxy client before the response is terminated, to be synchronous.

**Comment by dkarlovi** [comment]
So, if I understood you correctly, the client is actually not async if I call `CacheManager::flush()` mysefl?

**Comment by dbu** [comment]
the http client is always "async", as in "able to send multiple requests in parallel". flush() however always waits for those requests to terminate, so once flush() returns, the caches have received the invalidation requests. afaik varnish handles invalidation without race conditions, for symfony http cache i am sure that there is no async handling so once the invalidation request is terminated, the cache is updated.

**Comment by dkarlovi** [comment]
Alright, let's close here then, I'm already calling `flush()` so something else is causing this issue for me probably.

Thank you for your explanations! :1st_place_medal:

**Comment by dbu** [comment]
good luck debugging! if you find something we could tweak in either the code or also in the documentation, don't hesitate sending a pull request ;-)

**Comment by dkarlovi** [comment]
Thanks!

You seem to be right, digging further into it, the invalidation requests from the cache manager are definitely sent before my assertions, but since my tests fail or pass randomly on subsequent runs without any code changes, it really does look like some sort of race condition... somewhere. This will be fun. :see_no_evil:

**Comment by dbu** [comment]
are you using https://github.com/FriendsOfSymfony/FOSHttpCache/blob/master/src/Test/VarnishTestCase.php ? i think we have this restart the varnish binary between every test, to have complete test isolation: https://github.com/FriendsOfSymfony/FOSHttpCache/blob/56dd01d382f390a866aed955f10f09f28b58dd6e/src/Test/Proxy/VarnishProxy.php#L91-L92

if you don't maybe varnish itself is doing things asynchronously (or you don't invalidate what you thought you invalidate)

**Comment by dkarlovi** [comment]
I definitely invalidate what I intend to, otherwise it would never work. **Varnish is 100% doing the purge async**, if I add `usleep(10000);` before doing the final request, cannot reproduce the issue anymore.

I'm not using the test case since my environment is started by Docker Compose, I could in theory ping the Varnish container to restart, but it would make the tests run forever. Maybe there's a way to send a `SIGHUP` or something to the process to make it flush its cache, but I'd expect it would again be async (since it would probably reuse the same mechanics it uses now).

Restarting the daemon seems like the most correct solution, but it's a cure that's worse than the disease, in my case. :laughing:

**Comment by dbu** [comment]
if you can create a blocking call to trigger SIGHUP on varnish, that should be reasonably quick and do the trick. if you keep the same cache between tests, you could have all kind of odd interactions, like a failing test not cleaning up after itself and then subsequent tests being wrong. or forgetting to invalidate something and then have things depend on previous tests.

**Comment by dkarlovi** [comment]
`varnishd` does seem to [support `SIGUSR1` which should flush everything](https://varnish-cache.org/docs/6.1/reference/varnishlog.html#signals), this might be a way forward actually. :thinking: 

You might be on to something, if this works, I owe you at least one :beer:

**Comment by dkarlovi** [comment]
Of course, the unfortunate thing is I now need to figure out how to send a signal from one container to another instead of, you know, do a simple HTTP request ... TO A HTTP SERVER! :see_no_evil:
