### ISSUE TITLE
Symfony 5.1 support

### ISSUE THREAD

**Issue by Camacojo** [FriendsOfSymfony/FOSHttpCacheBundle#546]
Would it be possible to support Symfony 5.1? I would really like to use this package for the project I just started.

**Comment by dbu** [comment]
hi, the version constraint of the bundles says `^5.0` for [https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/composer.json#L26-L28](the symfony dependencies), which means it can be installed with any version of symfony that is 5.x. 

does that answer your question, or did you run into any issues when installing with symfony 5.1?

**Comment by Camacojo** [comment]
@dbu Thanks for the quick reply, my composer error message made me think it was compatible up to Symfony 5.0, but I misread it completely. Got it working now!

**Comment by dbu** [comment]
semver usually means when something is fine with 5.0 it should be good with 5.1 as well. great that it works now!
