### ISSUE TITLE
 session_write_close(): Failed on /_fos_user_context_hash 

### ISSUE THREAD

**Issue by revollat** [FriendsOfSymfony/FOSHttpCacheBundle#572]
Hello I have hundreds of session failed errors, resulting with csrf error at login but I don't know where to invetsigate ? 
Any idead ?

**Comment by dbu** [comment]
hi @revollat , this is the issue tracker for bug reports and feature requests, not a support forum. in general, i recommend to first find out if the csrf errors are related to the caching or if people try to login without having loaded the page first (which would be the csrf doing what it is meant to do). if its legitimate logins, identify what factor makes the problem happen. does it not happen when user context hashing is disabled? does it always happen when the bundle is here, or only sometimes? do you find other errors in the logs that could give an indication. does the hash lookup call work when you simulate it with curl?

**Comment by dbu** [comment]
good luck. please update this ticket if you find something, even if the problem was elsewhere, in case others search with a similar problem.
