### ISSUE TITLE
Fastly support

### ISSUE THREAD

**Issue by NicoImparfait** [FriendsOfSymfony/FOSHttpCacheBundle#585]
Fos Http Cache supports Fastly as a proxy client but it is not configurable in fos http cache bundle.

It would look like:

```
fos_http_cache:
    proxy_client:
        fastly:
            service_identifier: '<my-app-identifier>',
            authentication_token: > '<user-authentication-token>',
            soft_purge: false
```

**Comment by dbu** [comment]
yep, fastly support was added later on, and it seems nobody built the configuration in the bundle yet. do you want to contribute this?

to build it, inspiration can be taken from the existing options like varnish, creating a new configuration section and service files to load in https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/tree/2.x/src/Resources/config

**Comment by DemigodCode** [comment]
Just created a PR https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/pull/597

**Comment by DemigodCode** [comment]
@dbu think we can close this issue

**Comment by dbu** [comment]
oh indeed, thanks! 

done in #597
