### ISSUE TITLE
scan code for legacy things

### ISSUE THREAD

**Issue by dbu** [FriendsOfSymfony/FOSHttpCacheBundle#602]
search for
* `@deprecated`
* PHP_VERSION_ID
* Kernel::MAJOR_VERSION
* class_alias
* method_exists

* scan the documentation for deprecated / legacy / versionadded and clean up

(not necessarily one huge pull request but smaller requests to fix things one-by-one)

**Comment by dbu** [comment]
part has been done in #617

**Comment by usu** [comment]
Also search for
- class_exists

**Comment by dbu** [comment]
fixed in #625 - the remaining class_exists are for optional dependencies.
