### ISSUE TITLE
Replace styleci with php-cs-fixer

### ISSUE THREAD

**Issue by usu** [FriendsOfSymfony/FOSHttpCacheBundle#623]
I'd suggest we replace styleci with php-cs-fixer to make it easier for auto-formatting during local development

Similar as done in FOSHttpCache in commit https://github.com/FriendsOfSymfony/FOSHttpCache/commit/944b8598a34c3485073895fa9685a79cdfbc35cf

**Comment by dbu** [comment]
yes, i agree. i also think php-cs-fixer is more up to date with rules.

do you want to do the MR for this? after merging, i will remove the styleci hook

**Comment by usu** [comment]
Yeah, I can do a PR for this. I suggest we try to merge #622 and #618 beforehand to avoid too many merge conflicts

**Comment by dbu** [comment]
fixed in #626
