### ISSUE TITLE
Unhandled match case

### ISSUE THREAD

**Issue by mankej** [FriendsOfSymfony/FOSHttpCacheBundle#629]
https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/d9606c656c0bc4d81ca8130c7fb3fca572dce93c/src/EventListener/AttributesListener.php#L41
If there are other attributes, this listener is raising the error 'Unhandled match case'. IMHO there needs to be a default case :)
I was forced to downgrade package :)

**Comment by dbu** [comment]
oh, i think you are right. thanks for reporting this regression. was not aware that match works like this - though it makes sense to avoid accidentally overlooking cases. adding the default case in #630 - can you test that branch in your project and report if that fixes the issue? if it does i will merge and release.

**Comment by RichardJong** [comment]
Same here, #630 fixes the issue :+1:

**Comment by dbu** [comment]
thanks for reporting. i just released the fixed version: https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/releases/tag/3.0.1
