### ISSUE TITLE
bug: Versions higher than 3.0.1 are not marked as stable on Packagist

### ISSUE THREAD

**Issue by Crovitche-1623** [FriendsOfSymfony/FOSHttpCacheBundle#632]
Hi,

I would like to install the version 3.5 of FOSHttpCacheBundle to make disappear the following deprecation :
```
"The "Symfony\Component\HttpKernel\DependencyInjection\Extension" class is considered internal since Symfony 7.1, to be deprecated in 8.1; use Symfony\Component\DependencyInjection\Extension\Extension instead. It may change without further notice. You should not use it from "FOS\HttpCacheBundle\DependencyInjection\FOSHttpCacheExtension".
``` 
However, I cannot write `"friendsofsymfony/http-cache-bundle": "^3.5"` in my `composer.json` file because my project requires `stable` as `minimum-stability`.

I saw on https://packagist.org/packages/friendsofsymfony/http-cache-bundle that only `3.x-dev` is available for install. Does that mean that version above 3.0.1 are non stable ?

Thanks in advance

**Comment by Crovitche-1623** [comment]
Nevermind, I think the PR #631 has already solved that problem... I will just wait for the next release.

**Comment by dbu** [comment]
thanks for the reminder - i never tagged a release with that cleanup. its always difficult to know when more changes will follow and when nothing happens anymore. and when nothing happens, i don't remember to tag a release...

anyways, here you go https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/releases/tag/3.0.2

**Comment by Crovitche-1623** [comment]
Thank you @dbu !
