### ISSUE TITLE
Docs refer to "latest" but should refer to "stable" instead

### ISSUE THREAD

**Issue by mvhirsch** [FriendsOfSymfony/FOSHttpCacheBundle#634]
By clicking on the link on [github's page](https://github.com/FriendsOfSymfony/FOSHttpCacheBundle)  under "about"[foshttpcachebundle.readthedocs.io](http://foshttpcachebundle.readthedocs.io/) I'll get redirected to "latest" documentation.

![image](https://github.com/user-attachments/assets/7c2f1a17-a4b3-439d-8901-2179e2c384c0)

 But "latest" [suggests to install an abandoned bundle `sensio/framework-extra-bundle`](https://foshttpcachebundle.readthedocs.io/en/latest/overview.html#requirements).

The proper documentation for v3 will be found under ["stable"](https://foshttpcachebundle.readthedocs.io/en/stable/overview.html). Is it possible to reconfigure the redirection, so users see "stable" instead of "latest" first? Or is it possible to point "latest" on [default branch `3.x`](https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/branches)?

**Comment by dbu** [comment]
i changed the configuration on readthedocs to show `stable` by default. thanks for updating the config, i hope latest now shows the right thing too.

**Comment by mvhirsch** [comment]
@dbu I now get redirected to _stable_ which solves this issue. Thank you very much! 

Unfortunately [latest still suggests](https://foshttpcachebundle.readthedocs.io/en/latest/overview.html#requirements) to install SensioFrameworkExtraBundle. Looks like #635 did not fix it. Any ideas?
