### ISSUE TITLE
RuleMatcher for TagSubscriber, InvalidationSubscriber

### ISSUE THREAD

**Issue by dbu** [FriendsOfSymfony/FOSHttpCacheBundle#69]
we should allow to configure a global RuleMatcher in the tag_listener section instead of hardcoding the response codes (see [TagSubscriber $response->isSuccessful](https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/EventListener/TagSubscriber.php#L71)).

i would only allow the match_response and the additional_cacheable_status options i guess, matching the request makes no sense for tags.

**Comment by ddeboer** [comment]
Our scenarios are the following.

1. Cache-Control: should only be set if response is *cacheable* (and request matches0.
2. Invalidation: should only be done if response is *successful*.
3. Tags: should be set if response is *cacheable* and invalidated if response is *successful*.

It makes sense for us to have some sane default for cacheable (RFC 7231) and successful (either 2xx or both 2xx and 3xx). Users should then be able to override these defaults through their configuration. 

Should we have introduce one ResponseMatcher that has `isCacheable()` and `isSuccessful()` or have two separate matchers?

**Comment by dbu** [comment]
lets keep them separate to make them more clear.

**Comment by wickedOne** [comment]
ok, so if i understand correctly you want one or more 'global' match configurations for both request and response which in conjunction define whether or not the response should be cached or be invalidated?

if so, a couple of questions:
- do they overrule the conditions configured in the the ``tags.rules``, do the ``tags.rules`` overrule the 'global' configs, or do they have to be merged upon making that decision (i.e. if you have the ``POST`` method configured in the 'global' rule and the ``PUT`` method in a ``tags.rules.match`` configuration, does the ``request.method`` have to match ``POST``, ``PUT`` or both)?
- do you want a ``ResponseMatcher`` like symfony's ``RequestMatcher`` and if so, what would be the typical properties to match (i assume response code would be one of them)?

**Comment by dbu** [comment]
if i remember correctly, the idea was to use a matcher that would decide whether a response is cacheable or not. if it matches the response, it is cacheable otherwise not. so its not about which tags to apply, but about the status to return.

we brainstormed some additional interfaces in the discussion. we already have a RuleMatcher that adds response handling to the RequestMatcher. but we might want to split that into interfaces that can say whether a response `isCacheable` and whether it `triggersInvalidation`. those could be used in all places we currently use the request::isSuccessful and response status code checks.

**Comment by wickedOne** [comment]
based on [this](https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/issues/241) issue, i assumed there should be a possibility to configure a matcher at a higher and more generic level in the configuration and just wondering whether the ``Tag`` matches should lose the possibility to, for instance, have the ``additional_cachable_status`` config or whether it should work together with the generic one.

so something like
```yaml
tags:
  enabled: true
  expression_language: app.expression_language
  response:
    additional_cacheable_status: [201]
  rules:
    -
      match:
        path: ^/foo
        additional_cacheable_status: [418]
```

**Comment by dbu** [comment]
merging several matchers can become really complicated to understand, and semantics are not as clear as i would like them. ideally the world would become simpler with version 2, not more complicated. imho, if an application has different logic what is e.g. a cacheable status, the rules might not be a good system anymore and people should just let the controller tag. or write a custom listener that has their domain logic built in.

so my idea would be that we have one matcher that determines whether a response should be tagged or trigger tag invalidation, and another one for the caching / invalidation subscriber. the individual rules are only about which tags to place where, not about deciding whether its successful or not. would that make sense to you?

**Comment by wickedOne** [comment]
i completely agree with you on the complexity part and whether rule matchers are the way to go for an application which needs different configurations for different routes…

in regard to BC, should i make an effort to get this into a 1.[4-5].x release or will this typically be part of a 2.x release (as labeled)?

**Comment by dbu** [comment]
lets go for version 2, its much easier there. we don't intend to do any
more 1.x minor versions, only bugfixes.
